### ISSUE TITLE
error on wp core install task

### ISSUE THREAD

**Issue by bastian-w** [Mixd/wp-deploy#101]
Hi, 
i am getting an error while running bundle exec cap production wp:setup:remote
i also have this error while running this wp:setup:local
DB config in database.yml are correct. 

    Running /usr/bin/env wp core install --url='http://www.myurl.com' --title='title.' --admin_user='admin' --admin_password='****' --admin_email='my@email.com' as sshuser@myurl.com
    (Backtrace restricted to imported tasks)
    cap aborted!
    SSHKit::Runner::ExecuteError: Exception while executing as sshuser@myurl.com: wp exit status: 1
    wp stdout: Nothing written
    wp stderr: Error: 
    <h1>Error establishing a database connection</h1>
    <p>This either means that the username and password information in your <code>wp-config.php</code> file is incorrect or we can't contact the database server at <code>localhost</code>. This could mean your host's database server is down.</p>
    <ul>
	    <li>Are you sure you have the correct username and password?</li>
	    <li>Are you sure that you have typed the correct hostname?</li>
	    <li>Are you sure that the database server is running?</li>
    </ul>
    <p>If you're unsure what these terms mean you should probably contact your host. If you still need help you can always visit the <a href='https://wordpress.org/support/'>WordPress Support Forums</a>.</p>

    SSHKit::Command::Failed: wp exit status: 1

**Comment by InnerSpark** [comment]
Make sure your host address is set to localhost in your database.yml.

Should look like this.

    local:
        host: localhost
        database: your-database-name
        username: your-user
        password: your-pass
    staging:
        host: localhost
        database: your-database-name
        username: your-user
        password: your-passproduction:
   host: localhost
        host: localhost
        database: your-database-name
        username: your-user
        password: your-pass

**Comment by bastian-w** [comment]
@InnerSpark everything is set correct here. The generated wp-config.php looks good i think. it stays in the root folder of the project. 
locally i run a MAMP Server. The $PATH additions are also made.

**Comment by bastian-w** [comment]
production server runs well by the way.

**Comment by lukewhitehouse** [comment]
@bastian-w Out of curiosity can you try changing your sitetitle to something without a special character? I know I've had problems in the past with quotes not escaping correctly but I wonder if its the same with others? Let me know how you get on.

Also it sounds silly but have you created a local database?

**Comment by bastian-w** [comment]
@lukewhitehouse 
done, and no changes. same error.
database exists. if i copy the generated wp-config.php in my project root to the local webserver folder after i done a manual wp core download command everything works fine. then i only need to enter the site name, admin user etc. after accessing it via browser.

i think there is something wrong with my local mysql. i tried
	
    ps -awwx | grep mysql

and i got:

    81721 ?? 0:00.04 /bin/sh /Applications/MAMP/Library/bin/mysqld_safe --defaults-file=/Applications/MAMP/tmp/mysql/my.cnf --port=3306 --socket=/Applications/MAMP/tmp/mysql/mysql.sock --user=mysql --pid-file=/Applications/MAMP/tmp/mysql/mysql.pid --log-error=/Applications/MAMP/logs/mysql_error.log --tmpdir=/Applications/MAMP/tmp/mysql/tmpdir --datadir=/Library/Application Support/appsolute/MAMP PRO/db/mysql
	82021 ?? 0:00.46 /Applications/MAMP/Library/bin/mysqld --defaults-file=/Applications/MAMP/tmp/mysql/my.cnf --basedir=/Applications/MAMP/Library --datadir=/Library/Application Support/appsolute/MAMP PRO/db/mysql --plugin-dir=/Applications/MAMP/Library/lib/plugin --user=mysql --tmpdir=/Applications/MAMP/tmp/mysql/tmpdir --log-error=/Applications/MAMP/logs/mysql_error.log --pid-file=/Applications/MAMP/tmp/mysql/mysql.pid --socket=/Applications/MAMP/tmp/mysql/mysql.sock --port=3306
	82098 ttys003 0:00.00 grep mysql


but when i try to 

    $ mysql --database=<dbname> --user=<username> --password=<password>
    ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)


as i said, via my browser i have a db connection, but via terminal i don't got one. i am using MAMP Pro on OSX 10.10.5

**Comment by bastian-w** [comment]
i'll try another approach today and add a vagrant stack to my project folder and creating symlinks to the public folder. MAMP sucks anyways ;)

**Comment by bastian-w** [comment]
ok i fixed it.
Problem was that my local wp used my system php and not the MAMP php version. 
i had to update my /etc/paths file and had to add the php bin path of my MAMP php before the /usr/bin 
after running

    wp --info

it said it uses my MAMP PHP and now it works.
