### ISSUE TITLE
Running wp-cli commands remotely

### ISSUE THREAD

**Issue by jmac** [Mixd/wp-deploy#102]
Hey there,

I'm using (and very much enjoying!) wp-deploy, but have come across an issue that I'm sure is quite straightforward but I am stuck on.

I'm trying to run `wp media generate` on the remote server. I've written a cap task for it:

```ruby
namespace :wp do

  desc "Regenerate thumbnails"
  task :regenerate_thumbnails do
    on roles(:web) do
      within release_path do
        execute :wp, "media regenerate --yes"
      end
    end
  end

end
```

It reports back with a success message:

```shell
$ bundle exec cap production wp:regenerate_thumbnails
INFO [b7a6bef9] Running /usr/bin/env wp media regenerate --yes as username@website.com
INFO [b7a6bef9] Finished in 164.408 seconds with exit status 0 (successful).
```

...however the thumbnails are most certainly _not_ being regenerated.

When I try and run `wp cli` commands on the remote server via ssh, I get a bit more info:

```shell
Found 102 images to regenerate.
Warning: Can't find "BlackBookTees1" (ID 586).
Warning: Can't find "BlackbookTees2" (ID 585).
Warning: Can't find "Carhartt1" (ID 582).
Warning: Can't find "Carhartt2" (ID 581).
Warning: Can't find "Carhartt3" (ID 580).
Warning: Can't find "lab9" (ID 576).
Warning: Can't find "lab8" (ID 575).
Warning: Can't find "lab7" (ID 574).
[clipped]
Success: Finished regenerating all images.
```

Again, no thumbnails are regenerated. It appears that all attachments are found in the db but not in the filesystem.

I'm wondering if it has something to do with wp-deploy's non-standard WordPress folder structure for uploads. Do you know if there's a way I can get around this?

Thanks very much in advance.

Cheers,

John

**Comment by lukewhitehouse** [comment]
Hi @jmac, sorry for the delay in getting back to you! I've never actually used this command before however it does sound like its not finding the images, most likely because of the location of the correct `content` folder as you so rightly mentioned.

Looking at [the docs](http://wp-cli.org/commands/media/regenerate/) it seems you can pass the global parameter `--path=<path>` where `<path>` would be the location to the correct uploads folder. Worth a try?

**Comment by jmac** [comment]
No probs at all @lukewhitehouse! Thanks for the reply. I figured the `--path` flag was the WP installation path, but will give it a shot pointing it at the uploads folder directly.

Cheers,

John
