### ISSUE TITLE
Setting correct site language after install

### ISSUE THREAD

**Issue by DrizzlyOwl** [Mixd/wp-deploy#103]
This could be defined in your initial `deploy.rb` under Setup WordPress as:
`set :wp_language, 'en_GB' # Your chosen site language`

You can then run `wp core language install <lang>` to install a new language if the language differs from `en_US` which is the default language for the WordPress repository.
(All language options can be found here: https://gist.github.com/DrizzlyOwl/c2f64b0286e34fe13122)

You will need to create a new folder called `languages` for WP to save the dictionary to.

**Comment by lukewhitehouse** [comment]
Cheers @DrizzlyOwl, added it to the list!
