### ISSUE TITLE
Plugin compatibility problems and others issues

### ISSUE THREAD

**Issue by robertocinetto** [Mixd/wp-deploy#104]
I'm experiencing in these days a little bit of frustration. I love Wp-Deploy but i've found that many times there are some problems: all these problems I think are caused by the change of the default WP structure (i'm talking about "content" and "wordpress" folder).

For example I've a theme that in a standard installation is perfect but in a wp-deploy has some problems. The problem was in how the theme creates paths. And i think that these problems exist in a lot of plugins too (i'm trying to find a plugin for simply upload files from the frontend and i can't find one that works...).

1- Do you have any suggestion on how to fix issues like these? 
2- Is a good idea create an archive where put the Wp-Deploy tested resources?

**Comment by robertocinetto** [comment]
Ok i've read the mega thread and i've read about the WP_CONTENT_DIR problem. So i would like to know if anyone have found some kind of solution like a good system configuration or any other fix?

**Comment by lukewhitehouse** [comment]
Hi @robertocinetto, unfortunately the problem with `WP_CONTENT_DIR` is more than likely always going to stay as all hosting environments are different. There may very well be a way to detect whether or not a server is configured to use `dirname(__FILE__)` or `$_SERVER['DOCUMENT_ROOT']` however, so if you do find anything let us know.

I'll close this for now as it sounds like you've found the solution for your problem. Let me know if theres anything else you're having problems with! :)
