### ISSUE TITLE
Permissions: mkdir

### ISSUE THREAD

**Issue by jmatc** [Mixd/wp-deploy#105]
Having a bit of frustration with this.  I am deploying via a sudoer, and am getting the following:

(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as [user@domain]: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: mkdir: cannot create directory ‘[project_directory]’: Permission denied
mkdir: cannot create directory ‘[project_directory]’: Permission denied

SSHKit::Command::Failed: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: mkdir: cannot create directory ‘[project_directory]’: Permission denied
mkdir: cannot create directory ‘[project_directory]’: Permission denied

Tasks: TOP => deploy:check:directories
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as [user@domain]: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: mkdir: cannot create directory ‘[project_directory]’: Permission denied
mkdir: cannot create directory ‘[project_directory]’: Permission denied

As I mentioned, my user has sudo privelages.  I tried changing ```use_sudo : true```, and to no avail, still getting the same error.

Can you please try assisting me?

Thanks in advance!

**Comment by lukewhitehouse** [comment]
@jmatc sounds like you don't own the folders you're trying to create stuff within. Try using `ls -la` within your directory and checking who owns that folder, then you may need to use the `chown` command to sort that out. Let me know how you get on.

**Comment by TheAggressive** [comment]
I'm also having this trouble. I did some tries in the command line on the server. If I type `sudo mkdir something ` it will make the Directory. Without `sudo` it's the same permission denied output. 

The only way I have figured out how to make this work is by putting root user as the SSHUSER. But as wp-cli is used in some features, is that going to be a issue since root is used, I also it's not a good thing to have root doing those commands.

Any help would be appreciated

**Comment by TheAggressive** [comment]
I'll try to set `use_sudo : true` and see if that helps.

**Comment by lukewhitehouse** [comment]
Hi @TheAggressive, sounds like you've got some permissions issues. I wouldn't recommend using the root account for anything really, instead you'll want to setup a separate user that is only used for the deployment (and so is setup in your `environment.rb` file. The permissions this user should have is only the stuff it'll need for wpdeploy to work. i.e. access to the correct folders, access to write to those folders, etc etc. Hope that helps!

**Comment by lukewhitehouse** [comment]
Closing this ticket due to inactivity. Please raise a new issue if you still have a problem.
