### ISSUE TITLE
Mention installing theme after setup in README

### ISSUE THREAD

**Issue by crtvhd** [Mixd/wp-deploy#106]
It took me, yet again, way too many hours to figure out that I manually need to copy `wordpress/wp-content/themes/twentyfifteen` to `content/themes` in order to have a theme. Otherwise I'll be left with a blank page without any error messages, which is a nightmare to debug.

Just to be clear: Am I supposed to do so manually? If so, I'd prepare a pull request with an updated README to save me and probably some other users headache next time when setting up `wp-deploy`.

**Comment by roubenz** [comment]
This could be useful for you: http://wp-cli.org/commands/theme/install/

**Comment by lukewhitehouse** [comment]
@crtvhd completely agree, the `README.md` is very out of date and we're looking to update soon!

**Comment by crtvhd** [comment]
Good to hear @lukewhitehouse! If you're planning to update README sometime soon, I'll skip creating a PR then.

Looking forward to upcoming updates 👍

**Comment by lukewhitehouse** [comment]
@crtvhd Updated the readme and wiki :)
