### ISSUE TITLE
db:push

### ISSUE THREAD

**Issue by erickorozco** [Mixd/wp-deploy#107]
When I try to push my local db to production I get the following error:  
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as xxx@yyyy
: undefined method `name' for nil:NilClass

NoMethodError: undefined method `name' for nil:NilClass
my_project/lib/capistrano/tasks/db.cap:115:in `block (3 levels) i
n <top (required)>'
Tasks: TOP => db:push
(See full trace by running task with --trace)

I'm missing something?

 Thanks!

**Comment by DrizzlyOwl** [comment]
From a quick glance, it looks like you need to populate your SSH login
details into the config file

**Comment by lukewhitehouse** [comment]
@erickorozco Hey there, did you manage to get this sorted?

**Comment by lukewhitehouse** [comment]
Closing this ticket due to inactivity. Please raise a new issue should you continue to experience problems.
