### ISSUE TITLE
empty wp-config and .htaccess files

### ISSUE THREAD

**Issue by erickorozco** [Mixd/wp-deploy#108]
After successfully pushing from my local environment to the server I noticed that both, the .htaccess file and the wp-config file, are empty. Why is this happening?

**Comment by nibzo1** [comment]
did you find a solution to this?

**Comment by lukewhitehouse** [comment]
@erickorozco Hi there, did you manage to get this sorted? Apologies for the delay in getting to you but let me know if you found anything. Did you run the `wp:setup:remote` command before `deploy`?

**Comment by nibzo1** [comment]
not sure what the issue was but a it works for me now

**Comment by lukewhitehouse** [comment]
@nibzo1 How strange! Well let me know if you figure out what it was and I'll update our new [FAQ](http://github.com/mixd/wp-deploy/wiki/FAQ) section

**Comment by nibzo1** [comment]
@lukewhitehouse yes will do, it may have been permissions or something. I will run the setup & deploy from scratch on a new machine and see if it occurs again

**Comment by fanals** [comment]
I was also missing both files because my vhost was pointing to repo instead of current.

When I read in wiki: "repo_url Capistrano uses this to clone the repository onto the server" I immediately created the vhost pointing to that directory.

Maybe it can be specified below this line in the wiki that its just a cache folder and vhost should be pointing to the directory named current.

**Comment by lukewhitehouse** [comment]
@fanals good shout, might be worth adding in a bit more information on generally how Capistrano works.

**Comment by lukewhitehouse** [comment]
Adding this to the TODO list :)

**Comment by nibzo1** [comment]
I have started using this project again for a new site and I'm getting the empty wp-config.php and .htaccess issue again.

Did anyone find a solution?

Everything is deployed ok except these files. I can also see that in my project repository where I run the deploy command the wp-config file is created and has all the information in it.

**Comment by lukewhitehouse** [comment]
Hey @nibzo1 did you manage to get this sorted? I wasn't able to recreate your problem.

**Comment by lukewhitehouse** [comment]
Updated the [Installation guide](https://github.com/Mixd/wp-deploy/wiki/Installation) to reference the vhosts issue @fanals 

@nibzo1 please create a new issue if you continue to experience problems.
