### ISSUE TITLE
Minimum git?

### ISSUE THREAD

**Issue by ethanclevenger91** [Mixd/wp-deploy#109]
I'm running into some issues with an old version of git, but am happy to upgrade. I was wondering if anyone knew the minimum version required?

**Comment by lukewhitehouse** [comment]
Hi @ethanclevenger91 the minimum required version of Git in 1.7.3 :) Let me know if that helps!

**Comment by ethanclevenger91** [comment]
Awesome, thanks. Maybe that info has a place in the README?

**Comment by lukewhitehouse** [comment]
@ethanclevenger91 definitely, the README is very very out of date and the whole repo needs a refresh to be honest. Its on our radars don't worry! :)
