### ISSUE TITLE
Multisite compatibility with nginx

### ISSUE THREAD

**Issue by brianveltman** [Mixd/wp-deploy#110]
When I activate Multisite I am not able to access '/network'. This has something to do with nginx rewrite rules. I dove into it (https://codex.wordpress.org/Nginx) and I'm wondering what I should do for the wp-includes.

WordPress recommend:
```
location ~ ^/[_0-9a-zA-Z-]+/files/(.*)$ {
        try_files /wp-content/blogs.dir/$blogid/files/$2 /wp-includes/ms-files.php?file=$2 ;
        access_log off; log_not_found off; expires max;
}

#avoid php readfile()
location ^~ /blogs.dir {
        internal;
        alias /var/www/example.com/htdocs/wp-content/blogs.dir ;
        access_log off; log_not_found off;      expires max;
}
```

Does this refer to the wp-content and wp-includes directories within the git submodule or not? For the wp-content dir I don't think so.

Please advise.

**Comment by lukewhitehouse** [comment]
Hi @brianveltman unfortunately I'm not well versed in nginx at all so I wouldn't have the faintest idea. Just to give you some context, for apache servers we use [this line](https://github.com/Mixd/wp-deploy/blob/master/config/templates/wp-config.php.erb#L26) to set the correct location for `wp-content`, however, sometimes this doesn't work on all server setups as they cannot recognise the `$_SERVER['DOCUMENT_ROOT']`, therefore we have to use the line above instead. I'm not sure if thats related to your issue but let me know.
