### ISSUE TITLE
Deploy user

### ISSUE THREAD

**Issue by TheAggressive** [Mixd/wp-deploy#112]
Can someone explain the whole process of making a deployment user? Everything from start to finish. 

The very start `adduser deploy`

Thank you

**Comment by lukewhitehouse** [comment]
Hi @TheAggressive I'd love to help. By 'deployment user' are you referring to an SSH user's permissions?

**Comment by TheAggressive** [comment]
Yes, I've been trying to use this for about a week now. I keep running into permission issues. Also the db isn't being pushed up even when just pushing with db:push command it comes with errors. My setup is on a Windows machine using vagrant vvv.

Thank you for any help

**Comment by lukewhitehouse** [comment]
Hi @TheAggressive sorry for the delay in getting back to you, pretty manic in the office at the minute. Still got problems or manage to find a workaround? I don't actively use Vagrant at the minute (shocking I know!) but any insight would be great to put into the FAQ.

**Comment by lukewhitehouse** [comment]
Archiving, please create a new issue if you're still experiencing problems
