### ISSUE TITLE
How to use this project?

### ISSUE THREAD

**Issue by korobochkin** [Mixd/wp-deploy#114]
I'm a little confused with wp-deploy. Trying to start with wiki Installation and Usage guides but looks nothing wokring for me. I have already done:

  * Setted up VVV (with Bundler) from which I run all commands (as local web server). 
  * Remote shared hosting with SSH (auth by SSH-key) (Vagrant machine correctly log in into this server).

I stuck on Step 9 in Installation guide. What I need to do? I creating a new blank site without any data or existing DB.

If I run `bundle exec cap staging wp:setup:remote` command then I've got the following error:

```
INFO [13fbd071] Running /usr/bin/env curl -X POST --data-urlencode
	'payload={"channel":"#general","username":"Capistrano","text":"staging deploy
	of wp-deploy with revision/branch development failed","icon_emoji":":rocket:",
	"parse":"default"}' slack_token as vagrant@localhost
/var/lib/gems/1.9.1/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in
	`exit_status=': curl exit status: 1536 (SSHKit::Command::Failed)
curl stdout: Nothing written
```

**Comment by martisj** [comment]
Check out this issue. And comment out line #15 in your capfile. https://github.com/Mixd/wp-deploy/blob/v1.2.0/Capfile#L15

See https://github.com/Mixd/wp-deploy/issues/70 for the full run-down.

**Comment by korobochkin** [comment]
@martisj ah, thank you. Looks like I'm not very attentive 👍
