### ISSUE TITLE
pulling db from staging - issues running 'wp' locally

### ISSUE THREAD

**Issue by rfair404** [Mixd/wp-deploy#116]
I have successfully set up wp-deploy as far as I can tell. I'm able to deploy to both remote environments. 

Recently I have tried to do 'bundle exec cap staging db:pull' to pull my staging environment database into my local environment. 

I have wp-cli installed on my server, and locally. the error seems to be related to the fact that SSH.config.command_map[:wp] is specifying the "staging" path to wp-cli not the local path to wp-cli.

producing this error: 
```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as friendsschoolatb@67.227.201.200: No such file or directory - /home/friendsschoolatb/bin/wp-cli.phar
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Errno::ENOENT: No such file or directory - /home/friendsschoolatb/bin/wp-cli.phar
/usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/open3.rb:193:in `spawn'
/usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/open3.rb:193:in `popen_run'
/usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/open3.rb:93:in `popen3'
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/local.rb:63:in `block in _execute'
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/local.rb:58:in `tap'
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/local.rb:58:in `_execute'
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/local.rb:27:in `execute'
/Users/russell/vagrants/varying-vagrant-vagrants/www/fsa/new_htdocs/lib/capistrano/tasks/db.cap:94:in `block (4 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/local.rb:15:in `instance_exec'
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/local.rb:15:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:59:in `run_locally'
/Users/russell/vagrants/varying-vagrant-vagrants/www/fsa/new_htdocs/lib/capistrano/tasks/db.cap:93:in `block (3 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => db:pull
```

Any suggestions for how to make the "run_locally" block in lib/capistrano/tasks/db.cap lines 93 & 94 honor the local configurations? 

I created a "local.rb" inside of config/deploy and setting the SSH config

**Comment by rfair404** [comment]
I read the similar issues, in particular #43 which seem to deal with issues on the server. I can confirm that wp tasks on the remote machines are working just fine.

**Comment by DrizzlyOwl** [comment]
@rfair404 can you show us what is returned when SSH'd into your server and after running `wp --info`

**Comment by rfair404** [comment]
~/bin/wp-cli.phar --info
PHP binary:	/usr/local/bin/php
PHP version:	5.5.30
php.ini used:	/usr/local/lib/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	/home/friendsschoolatb/.wp-cli/packages/
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	0.23.1

**Comment by DrizzlyOwl** [comment]
As a pure observation the only thing I can see that differs from your output to mine is that you're using `phar://wp-cli.phar` I believe the script may be expecting to execute `wp` from `/usr/local/bin/wp` instead.

**Comment by rfair404** [comment]
I have tried that too. moved wp-cli.phar to ~/wp , /usr/local/bin/wp is
jailed in my server. the location of wp-cli on the server isn't the issue
AFAIK because it is the "run locally" portions aren't running well on my
local machine.

Thanks

On Tue, Jun 14, 2016 at 4:29 AM, Ash Davies <notifications@github.com>
wrote:

> As a pure observation the only thing I can see that differs from your
> output to mine is that you're using phar://wp-cli.phar I believe the
> script may be expecting to execute wp from /usr/local/bin/wp instead.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mixd/wp-deploy/issues/116#issuecomment-225813791>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AArmbkK_sKCx_wIFSkRff3e3y9Sjj3RNks5qLmZYgaJpZM4I0abE>
> .
>



-- 
Thanks,

Russell Fair
770.401.9039

**Comment by lukewhitehouse** [comment]
Hi @rfair404 when you installed wpcli locally did you follow the installation instructions about moving it into the `/user/local/bin/wp` as @DrizzlyOwl described?

More info here: https://wp-cli.org/

**Comment by rfair404** [comment]
yes, on my local machine wp lives in : /usr/local/bin/wp

on the servers, it is in another directory because I don't have permission
to put wp in /usr/local/bin/


On Tue, Jun 14, 2016 at 10:57 AM, Luke Whitehouse <notifications@github.com>
wrote:

> Hi @rfair404 <https://github.com/rfair404> when you installed wpcli
> locally did you follow the installation instructions about moving it into
> the /user/local/bin/wp as @DrizzlyOwl <https://github.com/DrizzlyOwl>
> described?
>
> More info here: https://wp-cli.org/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Mixd/wp-deploy/issues/116#issuecomment-225908738>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AArmbnzQapZoHiY72ywhAfUrsQ8u4Tezks5qLsE9gaJpZM4I0abE>
> .
>



-- 
Thanks,

Russell Fair
770.401.9039

**Comment by lukewhitehouse** [comment]
@rfair404 OK cool, and when running `wp --info` you can see your correct version of wpcli?

**Comment by lukewhitehouse** [comment]
Archiving, please create a new issue if you're still experiencing problems
