### ISSUE TITLE
Can change folder name content with any names?

### ISSUE THREAD

**Issue by nakamuraagatha** [Mixd/wp-deploy#117]
Can change folder name content with any names? i see this default folder wp-content change with content, can i change that with any names?

**Comment by lukewhitehouse** [comment]
@nakamuraagatha You can! Just make sure that you do this before you run `wp:setup:local` or `remote`. Also, you'll need to make the change within https://github.com/Mixd/wp-deploy/blob/master/config/templates/wp-config.php.erb#L17 and on Line [25 & 26](https://github.com/Mixd/wp-deploy/blob/master/config/templates/wp-config.php.erb#L25-L26) too
