### ISSUE TITLE
Deploy doesn't upload content/themes/{my_theme} nor content/plugins/{my_plugins}

### ISSUE THREAD

**Issue by sshaginyan** [Mixd/wp-deploy#118]
Hi folks!

So I can't get my theme nor plugins to upload remotely. I followed the installation instructions as stated on the page with no avail. 

_____Ruby______
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
_____Gems_____
Using rake 10.4.2
Using i18n 0.7.0
Using colorize 0.7.5
Using net-ssh 2.9.2
Using multi_json 1.11.0
Using bundler 1.11.2
Using net-scp 1.2.1
Using sshkit 1.7.1
Using capistrano 3.4.0
Using capistrano-slackify 2.2.0
Bundle complete! 2 Gemfile dependencies, 10 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by DrizzlyOwl** [comment]
Have you set the correct configuration for your GitHub repository in `deploy.rb`?

**Comment by lukewhitehouse** [comment]
Hey @sshaginyan can you go into your `deploy.rb` file and change the `log_level` from `info` to `debug` and then run the command again. Once done, paste it into for us to look into :)

**Comment by sshaginyan** [comment]
Hey @DrizzlyOwl got it fixed! For some reason :repo_url was overwritten with git@github.com:Mixd/wp-deploy.git.

Thanks @lukewhitehouse @DrizzlyOwl.

**Comment by lukewhitehouse** [comment]
Awesome! :)
