### ISSUE TITLE
404 not found domain.dev/wp-admin

### ISSUE THREAD

**Issue by ttomdewit** [Mixd/wp-deploy#120]
After successfully installing WordPress locally with `$ bundle exec cap staging wp:setup:local` and flushing permalinks (settings to `%category%/%postname%`) I get a **404 Not Found** when trying to access `domain.dev/wp-admin`. Instead I'm still forced to use `domain.dev/wordpress/wp-admin`.

**Comment by lukewhitehouse** [comment]
@ttomdewit again i have a feeling this may be to do with your PHP version just like #119 so lets fix that first and come onto this afterwards! "Will close this for now, lets deal with the other one :)
