### ISSUE TITLE
Cannot force update the current branch

### ISSUE THREAD

**Issue by deodigital** [Mixd/wp-deploy#123]
Hey, 

This relates back to issue 121 I'm still getting these errors when doing...

bundle exec cap staging wp:setup:remote

I've tried removing the repo folder and the temp folders, even tried a completely new repo.

SSHKit::Runner::ExecuteError: Exception while executing as user@server: git exit status: 128
git stdout: Nothing written
git stderr: stdin: is not a tty
fatal: Cannot force update the current branch.

SSHKit::Command::Failed: git exit status: 128
git stdout: Nothing written
git stderr: stdin: is not a tty
fatal: Cannot force update the current branch.

Tasks: TOP => git:create_release
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as user@server: git exit status: 128
git stdout: Nothing written
git stderr: stdin: is not a tty
fatal: Cannot force update the current branch.

**Comment by lukewhitehouse** [comment]
Apologies for not getting back to you in so long, it's pretty crappy management of an open source project. I'm going to close this but if you need anything at all please open up a new issue.
