### ISSUE TITLE
Failures to deploy with WP 4.6

### ISSUE THREAD

**Issue by JimChestnutt** [Mixd/wp-deploy#125]
There seems to be a problem with some wp deploy features (such as db:push) when using WordPress 4.6 and older versions of WP-CLI

It looks like the version of WP-CLI needs upgrading to 0.24 to be fully compatible with WordPress 4.6.

**Comment by DrizzlyOwl** [comment]
Fix for this is to ensure that the server you are deploying to has an up to date version of WP-CLI installed.
