### ISSUE TITLE
Should you and if so how do you update an existing WP Deploy

### ISSUE THREAD

**Issue by hihellosm** [Mixd/wp-deploy#126]
Say you're running a project on WP Deploy for a while, is it worth updating WP Deploy to be using the latest code? I Imagine this could be problematic, just thought I'd ask.

**Comment by lukewhitehouse** [comment]
@hihellosm sorry for the delay in getting back to you. There is currently no easy way of updating wpdeploy other than looking at the files changes and removing them.

Generally speaking its only ever tasks that are changed though so feel free to edit any of the files within `lib/capistrano/tasks`. Hope this helps!
