### ISSUE TITLE
db:push when proc_open is disabled on server

### ISSUE THREAD

**Issue by peerbolte** [Mixd/wp-deploy#128]
I have been happily using wp-deploy for a while now, but as we switched to a managed VPS provider I ran into an issue: for security reasons proc_open is disabled on the server. Apparently wp-cli needs proc_open in order to do database interactions such as import. 

To make import work without wp-cli i have changed: 
`execute :wp, "db import #{fetch(:backup_file)}"`
to
`execute "mysql -u #{database['username']} -p#{database['password']} -h #{database['host']} -D #{database['database']} < #{fetch(:backup_file)}"`

and added 
`database = YAML::load_file('config/database.yml')[fetch(:stage).to_s]`
right below `task :push do` 

This solves the issue, and allows me to deploy the local database to production. What are your thoughts on this? Is it worth a setting within wp-deploy to choose between mysql deployment or wp-cli db?

**Comment by lukewhitehouse** [comment]
HI @peerbolte thanks for letting us know about this. In the next release I believe we will switching to mysql db commands anyhow as the wpcli ones do not upload all tables, only ones part of WordPress. Not an issue for everyone but if you have any custom tables without your site's table prefix (usually `wp_`) then it does become one.

**Comment by peerbolte** [comment]
Good to hear you already have a solution for the next release. Do you have an ETA on the next release?

**Comment by lukewhitehouse** [comment]
@peerbolte I wouldn't want to say anything concrete yet but I'm definitely pushing for a Q1 2017 launch.
