### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by lustremedia** [Mixd/wp-deploy#133]
There are a couple of pull requests, and I think you should also move to the latest Capistrano version ... I am currently running 3.8.1 and it looks like it is doing fine so far.

Disclaimer: I have only been setting up deployment locally so far ...

Are we going to see any work on this done soon?

**Comment by robertocinetto** [comment]
👍🏻

**Comment by DrizzlyOwl** [comment]
Pull requests are welcome, but work is very limited on this project as it's not our primary focus at present. It's still maintained and hopefully we should be working on an update for you soon.

**Comment by lustremedia** [comment]
There are three pull requests pending. One of which is an easy fix to get the latest Wordpress Version. I have also been able to get my project to run with the latest Capistrano version and there is some newer git Gems that need to be incorporated.

**Comment by lukewhitehouse** [comment]
@lustremedia @robertocinetto I'm going to be working over the next week or so to get some much needed updates to wp-deploy out the door, you can follow my progress in the development branch.

While I'm at it, if you think there are any additions/changes you feel would be good to include at this stage please let me know by creating a new issue for each item to track. I'll close this issue now, thanks!
