### ISSUE TITLE
I created a project wp-deploy-easy

### ISSUE THREAD

**Issue by lustremedia** [Mixd/wp-deploy#139]
Hi @lukewhitehouse I started my own "hard fork" of wp-deploy with several improvements for my needs, but some could also benefit wp-deploy. It still needs work on the documentation. 
Do you have any concern with the project name or otherwise?
I am going to target mostly NGINX Webservers and try to keep web server configs to a minimum.
Have a look under: https://github.com/lustremedia/wp-deploy-easy

**Comment by lukewhitehouse** [comment]
Hi @lustremedia thats great, hopefully between our two projects we can move them both forward at a much quicker rate. Thanks for the attribution too, we'll do the same, always happy to support forks etc. No issues with the name in my opinion as long as the attribution is there :)
