### ISSUE TITLE
.wpignore What does it do?

### ISSUE THREAD

**Issue by Bodom78** [Mixd/wp-deploy#144]
I cannot find any reference in the deployment scripts to .wpignore and the items listed in it are not excluded from my deployments. Any more info on the use of this file?

**Comment by achilles283** [comment]
It doesn't do anything actually. You need to add a .gitattributes file to the root with the files you want excluded on deploy. I created a pull request with a fix for this.

See: https://github.com/Mixd/wp-deploy/pull/145

**Comment by Bodom78** [comment]
@achilles283 Excellent, I used export-ignore so I just wanted to confirm .wpignore was not required before I removed it.
