### ISSUE TITLE
Unable to specify port

### ISSUE THREAD

**Issue by stevebasford** [Mixd/wp-deploy#146]
I'm trying to specify a non standard ssh port and have done so by appending :PORT to the end of the stage_url as was advised in a prior issue. However when I run `bundle exec cap production wp:setup:remote` it throws `Operation timed out - connect(2) for ... port 22`.

Any ideas why it's not honouring the specified port?

**Comment by lukewhitehouse** [comment]
Hey @stevebasford you should be able to stick the following into your `ENVIRONMENTNAME.rb` file within `config/deploy/*`:

```
set :ssh_options, {
forward_agent: true,
port: YOURPORT
}
```

This is all standard Capistrano so check out the docs for more info, give us a shout if you need anything else.

**Comment by stevebasford** [comment]
Hmm I guess that worked, thanks! I'm getting a new issue now: `Net::SSH::Disconnect: connection closed by remote host`

I've got it going with another one of my servers fine so I'm not sure what's going on with this one (Siteground).

**Comment by lukewhitehouse** [comment]
@stevebasford Sounds like Capistrano can't connect to the server and is timing out. Possibly due to not being able to read your SSH keys? (I'm guessing tbh but have a look into that).

**Comment by stevebasford** [comment]
Managed to get it sorted. For anyone trying to get it working with Siteground shared hosting, you need to enter the server url rather than the ip and all seems to work fine.

Thanks for your help Luke :)
