### ISSUE TITLE
uploads:push timeout

### ISSUE THREAD

**Issue by stevebasford** [Mixd/wp-deploy#147]
Me again. I'm getting a time out when trying to push uploads to the server:

```
cap aborted!
SSHKit::Command::Failed: rsync exit status: 3072
rsync stdout: Nothing written
rsync stderr: ssh: connect to host ukm16.siteground.biz port 22: Operation timed out
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/io.c(453) [sender=2.6.9]
```

Everything else is working fine (deploy/db)

**Comment by lukewhitehouse** [comment]
@stevebasford Looks like your connection is timing out. My first instinct would be to try a different server like you did last time. Let me know what happens.

**Comment by stevebasford** [comment]
How would I try a different server for just the uploads? The deploy and database commands are working fine?

**Comment by stevebasford** [comment]
I'm guessing this may be down to the shared host restricting the max_execution_timeout so am closing this.
