### ISSUE TITLE
wp:plugins:pull

### ISSUE THREAD

**Issue by waynetheisinger** [Mixd/wp-deploy#149]
Hi 

I would like to give my users the ability to install plugins from the "Add New" button in the interface.. but still source control the plugins...

Therefore I need a wp:plugins:pull feature that works in a similar way to the wp:uploads:pull

I don't mind building this myself and will then do a pull request... but I just wondered why it doesn't exist... is there some implementation issue that I'm unaware of that stops one simply rsyncing the folder?

**Comment by lukewhitehouse** [comment]
Hey @waynetheisinger this would require the user to essentially have write privileges to the plugins folder and they could add existing plugin, some of which are not built very well and can leave your website exposed. In addition, in order for the plugins to be source controlled you would need a way for this to then be added to Git through a web hook.

This seems very custom to your personal needs and not something the vast majority of people using wp-deploy would require/want.

**Comment by lustremedia** [comment]
This could be done pretty straight forward. If the web server has the correct settings, the plugins could be added automatically on production. Pulling those plugins down into development could be handy. Adding could be then done locally with `git add` to source these or to toss them using `git checkout` after one has pulled them down. However deployment would still replace anything on production.

**Comment by lustremedia** [comment]
Another idea is to work with `wp plugin`. One could write a rake task that looks at production installed plugins `wp plugin list` and exports this list to locally and then installs them locally into the plugins folder.

**Comment by DrizzlyOwl** [comment]
Hello, unfortunately this is outside of the scope of this application and should be managed by your version control.
