### ISSUE TITLE
no alternative certificate subject name matches target host name 'core.git.wordpress.org'

### ISSUE THREAD

**Issue by slavajacobson** [Mixd/wp-deploy#152]
This issue started happening after we upgraded to v1.3.0.

`00:04 git:submodules:create_release
      01 git reset --mixed --quiet master --
    ✔ 01 useracc@xxx.xxx.xxx.xxx 0.195s
      02 git submodule update --init --checkout --recursive --quiet
      02 fatal: unable to access 'https://core.git.wordpress.org/': SSL: no alternative certificate subject name matches target host name 'core.git.wordpress.org'
      02 fatal: clone of 'git://core.git.wordpress.org/' into submodule path '/home/useracc/public_html/staging/new_site/site/releases/20180125225754/wordpress' failed
      02 Failed to clone 'wordpress'. Retry scheduled
      02 fatal: unable to access 'https://core.git.wordpress.org/': SSL: no alternative certificate subject name matches target host name 'core.git.wordpress.org'
      02 fatal: clone of 'git://core.git.wordpress.org/' into submodule path '/home/useracc/public_html/staging/new_site/site/releases/20180125225754/wordpress' failed
      02 Failed to clone 'wordpress' a second time, aborting
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as useracc@xxx.xxx.xxx.xxx: git exit status: 1
git stdout: Nothing written
**git stderr: fatal: unable to access 'https://core.git.wordpress.org/': SSL: no alternative certificate subject name matches target host name 'core.git.wordpress.org'**
fatal: clone of 'git://core.git.wordpress.org/' into submodule path '/home/useracc/public_html/staging/new_site/site/releases/20180125225754/wordpress' failed
Failed to clone 'wordpress'. Retry scheduled
fatal: unable to access 'https://core.git.wordpress.org/': SSL: no alternative certificate subject name matches target host name 'core.git.wordpress.org'
fatal: clone of 'git://core.git.wordpress.org/' into submodule path '/home/useracc/public_html/staging/new_site/site/releases/20180125225754/wordpress' failed
Failed to clone 'wordpress' a second time, aborting`

I have the latest curl installed 7.58.0 and when I run 
`curl https://core.git.wordpress.org/`
returns:
`curl: (51) SSL: no alternative certificate subject name matches target host name 'core.git.wordpress.org'`

When I visit https://core.git.wordpress.org/ from a browser, it tells me their SSL certificate is not valid. 

Is there a temporary workaround for this issue? Maybe it makes sense to switch to non secure URL until they fix their certificate problem?

**Comment by DrizzlyOwl** [comment]
Hi there, I've looked into this for you and it would seem the hostname core.git.wordpress.org is only applicable when referencing it over SSH using `git://core.git.wordpress.org` which is why you are seeing an invalid SSL certificate. It is discussed on [Trac](https://meta.trac.wordpress.org/ticket/1617).
