### ISSUE TITLE
Wordfence issues with .gitignore

### ISSUE THREAD

**Issue by kjbrum** [Mixd/wp-deploy#161]
I've been getting errors recently when trying to enable Wordfence. I believe the issue is because `xmlrpc.php` is an ignored file.

**Comment by DrizzlyOwl** [comment]
Hi @kjbrum, could you perhaps show me some log files that highlight this as being an issue?

**Comment by kjbrum** [comment]
Sorry for missing this.

@DrizzlyOwl, Wordfence has an `xmlrpc.php` file at the following path: `./vendor/wordfence/wf-waf/src/lib/xmlrpc.php`

Having `xmlrpc.php` in the `.gitignore` causes Wordfence to break since that file doesn't get deployed.
