### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by wopudev** [Mixd/wp-deploy#171]
Hi, is anyone working on this yet?

Sounds like a great project to me.

Do you recommend it for production?

**Comment by pointlessone** [comment]
I'm a user, not a maintainer of this project.

It's a rather simple setup. It covers all it set out to cover. There's not much that can be added/changed. Consider it stable.

Recommendation very much depends on whether your deployment target has a package for wp-cli. Not all linux distros have that and you'll have to either manually install it or create a package for wp-cli. Depending on your infrastructure policies that might be OK or a complete deal breaker. Decide for yourself.

**Comment by DrizzlyOwl** [comment]
Hi @wopudev. At the moment we have no further plans to continue development of WP Deploy - though we do still use it in production across a large majority of our websites and it is considered stable.

We have recently been developing an alternative tool written in PHP which makes use of [Deployer](https://deployer.org/) called [Packer WP](https://github.com/Mixd/PackerWP).
