### ISSUE TITLE
Bundle Capistrano tasks as a Ruby gem

### ISSUE THREAD

**Issue by wvteijlingen** [Mixd/wp-deploy#31]
I'm not a Ruby expert, but it seems to me that it would be really nice to have the Capistrano tasks in this framework bundled as a gem. This would make it easy to upgrade an existing project to a newer version if for example new tasks are added or existing tasks are updated.

**Comment by lukewhitehouse** [comment]
Hi @wvteijlingen to be honest, we're trying to get away from Ruby as much as possible really; mainly because its currently only used for Deployment.
