### ISSUE TITLE
Use a Capistrano config setting instead of a .wpignore file

### ISSUE THREAD

**Issue by wvteijlingen** [Mixd/wp-deploy#33]
I'm trying to clean up some of the file structure, and I think `.wpignore` is a good candidate for removal. I see these ignores as deployment configuration and thus I think it belongs in the config directory or an existing config file.

It think it would it be nice to replace the .wpignore file with a Capistrano `set` like this:

```ruby
set :wp_ignore, %w{/lib /config Capfile Rakefile Gemfile Gemfile.lock readme.md .gitattributes .gitignore .gitmodules}
```

Other pros of this is that ignores can be specified per environment if needed.

**Comment by lukewhitehouse** [comment]
I agree woith @hamishtaplin I like being able to easily access all the ignores within a single file – each on its own line; although perhaps theres already a convention out there for things like this. We'll look into it, cheers @wvteijlingen as always!
