### ISSUE TITLE
Issue with bundle exec cap dev db:push

### ISSUE THREAD

**Issue by sansgil** [Mixd/wp-deploy#38]
I'm trying to push my local DB onto my remote testing server but having no success. 

	bundle exec cap dev db:push
	 INFO [2e4a0d11] Running /usr/bin/env mkdir -p /home/mountyeti/dev.mountyeti.com/shared/db_backups on mountyeti.com
	DEBUG [2e4a0d11] Command: /usr/bin/env mkdir -p /home/mountyeti/dev.mountyeti.com/shared/db_backups
	 INFO [2e4a0d11] Finished in 1.997 seconds with exit status 0 (successful).
	 INFO [3a99de56] Running /usr/bin/env mkdir -p db_backups on
	DEBUG [3a99de56] Command: /usr/bin/env mkdir -p db_backups
	 INFO [3a99de56] Finished in 0.003 seconds with exit status 0 (successful).
	 INFO [b82b1b81] Running /usr/bin/env wp db export db_backups/2014102613845.sql --add-drop-table on
	DEBUG [b82b1b81] Command: /usr/bin/env wp db export db_backups/2014102613845.sql --add-drop-table
	cap aborted!
	wp stdout: Nothing written
	wp stderr: mysqldump: Got error: 2003: Can't connect to MySQL server on 'localhost' (61) when trying to connect

When I SSH into the server and run the command 

	/usr/bin/env wp db export db_backups/2014102613845.sql --add-drop-table

I get the following error 

	cd shared/
	[beehive]$ /usr/bin/env wp db export db_backups/2014102613845.sql --add-drop-table
	Error: This does not seem to be a WordPress install.
	Pass --path=`path/to/wordpress` or run `wp core download`.

**Comment by lukewhitehouse** [comment]
@sansgil still need help? sorry for the delay.

**Comment by sansgil** [comment]
@lukewhitehouse Yep, this is still a persistent issue.

**Comment by lukewhitehouse** [comment]
@sansgil By the looks of it its because your host is wrong. Does your hosting require a different `host` when you're connecting remotely? The servers we use internally do.

**Comment by stevenmorgan94** [comment]
I seem to be having the same problem. I'm just using the stock development and production environments.

 <addr>teven@Stevens-MBP DVDeploy (development) $ cap staging db:push
 INFO [029007c3] Running /usr/bin/env mkdir -p /var/www/vhosts/cubixllc.com/staging/staging.cubixllc.com/shared/db_backups on 70.32.112.199
DEBUG [029007c3] Command: /usr/bin/env mkdir -p /var/www/vhosts/cubixllc.com/staging/staging.cubixllc.com/shared/db_backups
 INFO [029007c3] Finished in 1.075 seconds with exit status 0 (successful).
 INFO [43796530] Running /usr/bin/env mkdir -p db_backups on
DEBUG [43796530] Command: /usr/bin/env mkdir -p db_backups
 INFO [43796530] Finished in 0.009 seconds with exit status 0 (successful).
 INFO [491c7c25] Running /usr/bin/env wp db export db_backups/20153914154.sql --add-drop-table on
DEBUG [491c7c25] Command: /usr/bin/env wp db export db_backups/20153914154.sql --add-drop-table
cap aborted!
wp stdout: Nothing written
wp stderr: sh: mysqldump: command not found
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/command.rb:94:in `exit_status='
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/backends/local.rb:49:in `block in _execute'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/backends/local.rb:36:in `tap'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/backends/local.rb:36:in `_execute'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/backends/local.rb:25:in `execute'
/Users/Steven/Desktop/DVDeploy/lib/capistrano/tasks/db.cap:62:in `block (4 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/backends/local.rb:13:in `instance_exec'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/backends/local.rb:13:in `run'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/dsl.rb:12:in `run_locally'
/Users/Steven/Desktop/DVDeploy/lib/capistrano/tasks/db.cap:60:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `run'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.3.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => db:push
(See full trace by running task with --trace)</addr>

**Comment by lukewhitehouse** [comment]
Hi @stevenmorgan94, to check that you do indeed have access to MYSQL, try running the following command when you're ssh'ed into your server; replacing the placeholders with your info:

```
mysql -h <host> -u <username> -p<password>
```

Notice no space between `-p` and `<password>`.
