### ISSUE TITLE
rewrite rule

### ISSUE THREAD

**Issue by MichaelKubovic** [Mixd/wp-deploy#39]
I guess that rewrite rule in .htaccess.erb template should point to /wordpress folder. Otherwise would `wordpress` end up in your url.
```
RewriteRule ^$ wordpress/index.php [L]
```

**Comment by lukewhitehouse** [comment]
Hi @MichaelKubovic Your site address is setup when you run `wp:setup:remote` or local. This is done by checking whether your site is locally on your system, in which case it will use the `wp_localurl` from [line 14](https://github.com/Mixd/wp-deploy/blob/master/config/deploy.rb#L14) of the `deploy.rb` file; or an environment, which would use [line 6](https://github.com/Mixd/wp-deploy/blob/master/config/deploy/production.rb#L6) of your environment file.
