### ISSUE TITLE
Change git checkout -B for CentOS/RHEL 6.4 stock version of git?

### ISSUE THREAD

**Issue by robolmos** [Mixd/wp-deploy#41]
* CentOS/RHEL 6.4 only packages git version 1.7.1.
* wp-deploy uses "git checkout -B" in submodule_strategy.rb.
* git checkout didn't learn -B until [version 1.7.3] (https://git.kernel.org/cgit/git/git.git/tree/Documentation/RelNotes/1.7.3.txt)

Can the submodule_strategy be changed to **git branch -f .. git checkout** to allow wp-deploy to work with the stock git package on CentOS/RHEL?

I know that CentOS/RHEL 6.6 is the latest 6.x version but I think some environments are still locked down to 6.4. They both use git 1.7.1 though.

Thanks

**Comment by aokolovskis** [comment]
Same on Debian 6.0

**Comment by bcole808** [comment]
Same issue on with Red Hat 6.6 using git version 1.7.1

When running deployment, throws the error: **error: unknown switch `B'**

I tested [pull request #53](https://github.com/Mixd/wp-deploy/pull/53) and can confirm that it resolved the issue for my server configuration.

**Comment by lukewhitehouse** [comment]
see #53
