### ISSUE TITLE
wp-deploy creates a duplicate path and then fails

### ISSUE THREAD

**Issue by coreyharrison** [Mixd/wp-deploy#42]
I'm trying to use `$ bundle exec cap production wp:setup:remote` to setup however it fails with the follow error:
`fatal: destination path 'var/www/example.com/public_html/repo' already exists and is not an empty directory.`

Oddly it creates a cloned file path inside of public_html, so the file structure end up looking like this:
<ul>
<li>var<li>
<ul><li>www</li>
<ul><li>example.com</li>
<ul><li>public_html</li>
<ul>
<li>releases (empty)</li>
<li>shared</li>
<ul>
<li>content</li>
<ul><li>uploads</li></ul>
<li>wp-config.php (blank)</li>
<li>.htaccess (blank)</li>
</ul>
<ul><li>var<li>
<ul><li>www</li>
<ul><li>example.com</li>
<ul><li>public_html</li>
<ul><li>repo</li>
<ul><li>everything in the repo
</ul></ul></ul></ul></ul></ul></ul></ul></ul></ul></ul></ul></ul>

Not sure what's going wrong so any pointers would be great.

**Comment by lukewhitehouse** [comment]
Hi @coreyharrison sorry for the delay, do you still need help?

**Comment by coreyharrison** [comment]
Hi @lukewhitehouse I ended up going with a different solution due to time constraints. But will look to using this again on my next project.

Thanks

**Comment by lukewhitehouse** [comment]
@coreyharrison No worries, let me know on [twitter](http://twitter.com/_lukewh) if you need help later down the line.

**Comment by kprovorov** [comment]
@coreyharrison Hi! Did you solve the problem of duplicating path? I have same one and have no idea what to do. My `staging.rb` looks like

```
set :stage, :staging
set :stage_url, "http://git.lp5.com.ua"
server "89.184.88.229", user: "gitMYe", roles: %w{web app db}
set :deploy_to, "git.lp5.com.ua"
```


my default file structure on staging server looks like:
- var
 - www
   - gitOUw
      - cgi-bin
      - tmp



and after i launch `bundle exec cap staging wp:setup:remote`  it creates structure like:

- var
 - www
   - gitOUw
     - **git.lp5.com.ua**
        - **git.lp5.com.ua**
          - **repo**
        - **releases**
        - **shared**
      - cgi-bin
      - tmp


so it duplicates the folder `git.lp5.com.ua` and in my treminal i have next messages:

```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as gitMYe@89.184.88.229: git exit status: 128
git stdout: Nothing written
git stderr: fatal: destination path 'git.lp5.com.ua/repo' already exists and is not an empty directory.

SSHKit::Command::Failed: git exit status: 128
git stdout: Nothing written
git stderr: fatal: destination path 'git.lp5.com.ua/repo' already exists and is not an empty directory.

Tasks: TOP => git:create_release => git:update => git:clone
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as gitMYe@89.184.88.229: git exit status: 128
git stdout: Nothing written
git stderr: fatal: destination path 'git.lp5.com.ua/repo' already exists and is not an empty directory.
```


If have any ideas would be great. Thanx

**Comment by coreyharrison** [comment]
Hi @kprovorov 
I ended up moving to roots.io for wp deployment. They have some great tools that are really well supported.
