### ISSUE TITLE
failed to find folder 

### ISSUE THREAD

**Issue by naorye** [Mixd/wp-deploy#44]
When executing `bundle exec cap staging wp:setup:remote`, I get the following error:
```
[88b80465] Running /usr/bin/env [ -d /home1/webdevea/public_html/staging/repo/.git ] on staging.myhousehold.co
DEBUG [88b80465] Command: [ -d /home1/webdevea/public_html/staging/repo/.git ]
DEBUG [88b80465] Finished in 3.686 seconds with exit status 1 (failed).
```
Capistrano can't find the `repo` folder. It might be an incorrect order of execution.

**Comment by lukewhitehouse** [comment]
Hi @naorye check that the `server` field within your `environment.rb` file is the correct path would be my first thought. Theres not much to go on without the full error transcript.
