### ISSUE TITLE
Avoid download full Wordpress repository 

### ISSUE THREAD

**Issue by stuzzo** [Mixd/wp-deploy#47]
Hi, I'm running wp-deploy in a project and when I clone my repo, it downloads all the Wordpress Repository, around 200MB, even if there's a link to a specific commit.
Is there a way to avoid this and checkout only the related commit or tag?

Thank you!

**Comment by lukewhitehouse** [comment]
As far as I'm aware, in order to be able to find the latest branches/tags of a repo, you must have the full repository cloned, so I don't think this is possible.

In any case, WordPress is like 30mb.

**Comment by jplhomer** [comment]
@stuzzo I'm running into the same issue. The `.git` repo is huge with the entire 20k+ commit history of WordPress. @lukewhitehouse is right about not being able to check out branches/tags from a shallow commit, though. I'm looking into options, but upgrading storage on my server in the meantime.

**Comment by lukewhitehouse** [comment]
@jplhomer I see your point with the Commit History. I don't think there's a solution but we'll investigate :)
