### ISSUE TITLE
Shared Hosting

### ISSUE THREAD

**Issue by geekwithbadge** [Mixd/wp-deploy#49]
I'm sorry to post this question here but I've attempted to research this everywhere else with no answer. I'm attempting to deploy to a shared hosting account and seem to be running into some issues. I get no errors back but yet I'm not seeing any folders created on the server nor does the DB:PUSH seem to work. Was just making sure if this will work with shared hosting accounts. 

Thanks

**Comment by adisos** [comment]
Do you have ssh access?

**Comment by geekwithbadge** [comment]
Yes I do. It looks like I'm connecting to my server as it places a git-ssh.sh file on my staging server. Yet I don't see any other files.

**Comment by geekwithbadge** [comment]
By the way, I installed wp-cli on my shared hosting account. I have jailed ssh access but nonetheless still access and able to do all file manipulations within the shell. I'm still studying Capistrano3 to determine my issue.

**Comment by lukewhitehouse** [comment]
Hi @geekwithbadge, did you manage to solve your problem? As with many Shared Hosting Accounts, getting the correct level of access can be tricky – let me know if you're still having trouble.
