### ISSUE TITLE
Escape rsync arguments command

### ISSUE THREAD

**Issue by adisos** [Mixd/wp-deploy#50]
I have this problem
```
DEBUG [cea5cdf7] Command: rsync -ar --filter=':- .wpignore' --exclude=.git* /var/www/example.com/repo/ /var/www/example.com/releases/20150125190422
DEBUG [cea5cdf7] 	zsh:1: no matches found: --exclude=.git*
```

Found this [topic](http://superuser.com/questions/420525/scp-with-zsh-no-matches-found)
Escaped [here](https://github.com/Mixd/wp-deploy/blob/master/lib/capistrano/submodule_strategy.rb#L32) with double backslash instead of only one, then everything worked perfectly.

**Comment by lukewhitehouse** [comment]
Hi @adisos we'll look into this, thanks!

**Comment by clov3rly** [comment]
I had the same problem, applied the same fix, worked perfectly.

**Comment by lukewhitehouse** [comment]
Cheers for the update @clov3rly
