### ISSUE TITLE
Shared Host – fatal: failed to stat

### ISSUE THREAD

**Issue by danielfuerst** [Mixd/wp-deploy#52]
Hi there,
I am running into an issue when i am trying to deploy Wordpress on my shared host. I do have ssh access and the log says following:

DEBUG [0a757712] Command: ( GIT_ASKPASS=/bin/echo GIT_SSH=/home/user/tmp/wpdeploy/git-ssh.sh /usr/bin/env git ls-remote git@bitbucket.org:bitbucketuser/wpdeploy.git )
DEBUG [0a757712] 	fatal: failed to stat '/home/user/..': Permission denied
DEBUG [0a757712] Finished in 0.049 seconds with exit status 128 (failed).

Maybe you have an idea, what the problem could be.

Best,
Daniel

**Comment by lukewhitehouse** [comment]
HI @danielfuerst, can you provide the full error code please, that'll give us a better idea of it. From just looking at the 3 lines you've shown here, I'd say you're either unable to create a link between your server and bitbucket, or you're able to add any files to `/home/user/`. Can I ask who you have hosting with? I know that Media Template accounts have problems with this.
