### ISSUE TITLE
Specify port

### ISSUE THREAD

**Issue by ahaywood** [Mixd/wp-deploy#56]
Is there a way to specify the port so that it doesn't use 22?

**Comment by lukewhitehouse** [comment]
Hi @ahaywood yes you can if you append the host to the end of the domain you supply within the `environment.rb` file. For example, if you wanted a port of *423555* on the production site, then you'd going into the [production.rb](https://github.com/Mixd/wp-deploy/blob/master/config/deploy/production.rb) file, and change it to: `set :stage_url, "http://www.example.com:423555"`.

Hope that helps!
