### ISSUE TITLE
cap aborted! Operation timed out - connect(2)

### ISSUE THREAD

**Issue by royscheeren** [Mixd/wp-deploy#58]
I'm getting this message when trying to deploy. A quick search tells me that updating SSHkit solves that problem. However when using SSHkit 1.5 or 1.6 I'm getting a whole new set of errors. 

Any ideas on how I could fix that?

**Comment by royscheeren** [comment]
Figured it out!

**Comment by clov3rly** [comment]
Always helpful to leave a comment on what was broken, and how you fixed it, for those coming down the path behind you ;)

**Comment by royscheeren** [comment]
I would have, if it wasn't for my own idiocracy. :) I had forgotten my host does not use ssh on the default port, so changing that fixed those issues.
