### ISSUE TITLE
issues setting up environments

### ISSUE THREAD

**Issue by bobstermyang** [Mixd/wp-deploy#60]
I have set everything up the way on the readme, but when I try to setup the environment , it runs but I have no idea what it's doing....

Here's the Log.
<addr>
bobbyyang@bobbywebdev:~/wp-deploy$ bundle exec cap production wp:setup:both
 INFO [4ce64aab] Running /usr/bin/env mkdir -p /tmp/wp-deploy/ on 191.239.40.71
 INFO [4ce64aab] Finished in 1.765 seconds with exit status 0 (successful).
 INFO Uploading /tmp/wp-deploy/git-ssh.sh 100.0%
 INFO [fc114621] Running /usr/bin/env chmod +x /tmp/wp-deploy/git-ssh.sh on 191.239.40.71
 INFO [fc114621] Finished in 0.237 seconds with exit status 0 (successful).
 INFO [15c5c89a] Running /usr/bin/env mkdir -p /tmp/wp-deploy/ on 191.239.40.71
 INFO [15c5c89a] Finished in 0.230 seconds with exit status 0 (successful).
 INFO Uploading /tmp/wp-deploy/git-ssh.sh 100.0%
 INFO [b75892d4] Running /usr/bin/env chmod +x /tmp/wp-deploy/git-ssh.sh on 191.239.40.71
 INFO [b75892d4] Finished in 0.228 seconds with exit status 0 (successful).
</addr>

**Comment by stevenmorgan94** [comment]
Looks like that's running successfully. Did you get an error anywhere? The command you ran is setting up the initial WordPress install with details from your /config/production.php file.

**Comment by lukewhitehouse** [comment]
Hi @bobstermyang, I'm going to echo what @stevenmorgan94 said; from what I can tell you've setup the environment successfully. To test this, visit the site and you should have a blank install of WordPress which you can setup.

**Comment by anastasialanz** [comment]
I'm having the same issue. 

```
⦗2.1.0p0⦘⦗master⦘⦗PML_3142⦘➤ bundle exec cap production deploy
 INFO [edd3b673] Running /usr/bin/env mkdir -p /tmp/PML_3142/ on 104.236.34.40
 INFO [edd3b673] Finished in 0.680 seconds with exit status 0 (successful).
 INFO Uploading /tmp/PML_3142/git-ssh.sh 100.0%
 INFO [7dd8619a] Running /usr/bin/env chmod +x /tmp/PML_3142/git-ssh.sh on 104.236.34.40
 INFO [7dd8619a] Finished in 0.043 seconds with exit status 0 (successful).
 INFO [76588ce7] Running /usr/bin/env mkdir -p /tmp/PML_3142/ on 104.236.34.40
 INFO [76588ce7] Finished in 0.040 seconds with exit status 0 (successful).
 INFO Uploading /tmp/PML_3142/git-ssh.sh 100.0%
 INFO [5fe74cac] Running /usr/bin/env chmod +x /tmp/PML_3142/git-ssh.sh on 104.236.34.40
 INFO [5fe74cac] Finished in 0.039 seconds with exit status 0 (successful).
```

I don't see a blank install of WordPress anywhere on my server.

**Comment by lukewhitehouse** [comment]
Hi @anastasialanz, the best way to debug this is to go into `config/deploy.rb` and change the `:log_level` to `:debug` rather than `:info`. Run the command again to see a more detailed error.

**Comment by anastasialanz** [comment]
@lukewhitehouse I ran it again and it says

```
⦗2.1.0p0⦘⦗development⦘⦗PML_3142⦘➤ bundle exec cap production wp:setup:remote
 INFO [9d2c71fa] Running /usr/bin/env mkdir -p /tmp/PML_3142/ on 104.236.34.40
DEBUG [9d2c71fa] Command: /usr/bin/env mkdir -p /tmp/PML_3142/
 INFO [9d2c71fa] Finished in 4.187 seconds with exit status 0 (successful).
DEBUG Uploading /tmp/PML_3142/git-ssh.sh 0.0%
 INFO Uploading /tmp/PML_3142/git-ssh.sh 100.0%
 INFO [1ddb6d71] Running /usr/bin/env chmod +x /tmp/PML_3142/git-ssh.sh on 104.236.34.40
DEBUG [1ddb6d71] Command: /usr/bin/env chmod +x /tmp/PML_3142/git-ssh.sh
 INFO [1ddb6d71] Finished in 0.047 seconds with exit status 0 (successful).
 INFO [24bed5a3] Running /usr/bin/env mkdir -p /tmp/PML_3142/ on 104.236.34.40
DEBUG [24bed5a3] Command: /usr/bin/env mkdir -p /tmp/PML_3142/
 INFO [24bed5a3] Finished in 0.047 seconds with exit status 0 (successful).
DEBUG Uploading /tmp/PML_3142/git-ssh.sh 0.0%
 INFO Uploading /tmp/PML_3142/git-ssh.sh 100.0%
 INFO [6922658b] Running /usr/bin/env chmod +x /tmp/PML_3142/git-ssh.sh on 104.236.34.40
DEBUG [6922658b] Command: /usr/bin/env chmod +x /tmp/PML_3142/git-ssh.sh
 INFO [6922658b] Finished in 0.046 seconds with exit status 0 (successful).
DEBUG [d03fb73f] Running /usr/bin/env git ls-remote git@github.com:WalltoWall/PML_3142.git on 104.236.34.40
DEBUG [d03fb73f] Command: ( GIT_ASKPASS=/bin/echo GIT_SSH=/tmp/PML_3142/git-ssh.sh /usr/bin/env git ls-remote git@github.com:WalltoWall/PML_3142.git )
DEBUG [d03fb73f] Finished in 0.048 seconds with exit status 127 (failed).
DEBUG [d03fb73f] 	/usr/bin/env: git: No such file or directory
DEBUG [d03fb73f] Finished in 0.048 seconds with exit status 127 (failed).
```

**Comment by anastasialanz** [comment]
@lukewhitehouse I figured it out. Git wasn't installed on the server.

**Comment by lukewhitehouse** [comment]
@anastasialanz Glad you've got it sorted! Any other questions create an issue and one of us will gladly help as soon as we can!
