### ISSUE TITLE
Themes and Plugins after upgrade to 4.1.1

### ISSUE THREAD

**Issue by cornelous** [Mixd/wp-deploy#61]
I upgraded WordPress to 4.1.1 on a new install of WordPress and now wpdeploy only works if I copy the themes and plugins into the wp-content directory instead of the desired content directory. Please kindly assist or give guidance or does WPDeply work with WordPress 4.1.1?

Thank you

**Comment by lukewhitehouse** [comment]
Hi @cornelous, wp-deploy does indeed work with WordPress 4.1.1, and we're using that version internally. How did you go about upgrading WordPress to 4.1.1? Did you use the capistrano command that comes with wp-deploy? `bundle exec cap <environment> wp:core:update`

**Comment by cornelous** [comment]
Hi 

Yes, I used the capistrano command, then it checked out 4.1.1, I did a git add . git commit on my local and git push to my remote then I did a cap deploy.

I wonder what I could be missing, I have been using wpdeply successfully for 2months now and now looking at launching 2 new sites and am stuck somehow because I cant seem to get it to work with 4.1.1

**Comment by lukewhitehouse** [comment]
Are you having the problem locally as well as in your remote environment @cornelous ?

**Comment by cornelous** [comment]
Hi Yes, its the same problem locally as well as on production. My skype is kreativeq we could chat. Thank you

**Comment by lukewhitehouse** [comment]
Best to keep everything on Github so people can refer to this thread if they come across similar issues.

Can you check that your `wp-config.php` is referencing the following:

```
define('WP_SITEURL','http://redkitewaste.dev/wordpress');
define('WP_CONTENT_URL', 'http://redkitewaste.dev/content');
```

**Comment by cornelous** [comment]
Hi Luke

Thanks I was missing this:-

define('WP_SITEURL', 'http://site.dev/wordpress');
define('WP_CONTENT_URL', 'http://site.dev/content');

**Comment by lukewhitehouse** [comment]
Glad I could help :)
