### ISSUE TITLE
Error on deploying new plugin

### ISSUE THREAD

**Issue by cornelous** [Mixd/wp-deploy#63]
Hi Luke

I am getting an error when trying to deploy a new plugin to my remote server. I get the error on cap deploy. The plugin is found at:- 
http://pogidude.com/plugins/popular-posts-tabbed-widget-for-jetpack/

Please the output I get:-

-----
Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@54.68.244.159: git exit status: 1
git stdout: No submodule mapping found in .gitmodules for path 'content/plugins/popular-posts-tab-widget-for-jetpack'
git stderr: Nothing written

SSHKit::Command::Failed: git exit status: 1
git stdout: No submodule mapping found in .gitmodules for path 'content/plugins/popular-posts-tab-widget-for-jetpack'
git stderr: Nothing written

Tasks: TOP => git:create_release
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as ubuntu@54.68.244.159: git exit status: 1
git stdout: No submodule mapping found in .gitmodules for path 'content/plugins/popular-posts-tab-widget-for-jetpack'
git stderr: Nothing written

**Comment by lukewhitehouse** [comment]
Hi @cornelous sorry for the delay, am I rigt in assuming that you're trying to add this new plugin as a submodule? If this is so, take a look at your `.gitmodules` file in the root of the project and check that your submodule is present. If so, and you're only getting the error when you deploy, then try deleting the `repo` folder on the server and try deploying again.

**Comment by lukewhitehouse** [comment]
Hi @cornelous, did you manage to get everything sorted?

**Comment by cornelous** [comment]
No, I never managed with his, ended up forgoing deploying that particular plugin. No worries mate. Thanks
