### ISSUE TITLE
Failures on `cap [env] wp:setup:remote`

### ISSUE THREAD

**Issue by 412andrewmortimer** [Mixd/wp-deploy#69]
I'm getting failures on `cap [env] wp:setup:remote`

https://gist.github.com/412andrewmortimer/91fc41a52e16e24de58a

And when I try to access my site it's not loading. Also I'm getting this weird redirect happening when I try to navigate to http://my.ip.address/wordpress/wp-admin:

It's redirecting to http://my.ip.address/wordpress/wp-admin/my.ip.address./wordpress/wp-login.php?redirect_to=http%3A%2F%2Fmy.ip.address%2Fwordpress%2Fwp-admin%2F&reauth=1

Any assistance would be greatly appreciated. Thanks!

**Comment by 412andrewmortimer** [comment]
I also don't understand these commands:

```
DEBUG [284a19b0] Running /usr/bin/env [ -L /var/www/html/releases/20150407134741/wp-config.php ] on 104.236.34.40
DEBUG [284a19b0] Command: [ -L /var/www/html/releases/20150407134741/wp-config.php ]
DEBUG [284a19b0] Finished in 0.046 seconds with exit status 1 (failed).
```

What kind of command is that? -L?

**Comment by clov3rly** [comment]
-L returns True if file exists and is a symbolic link.

https://www.gnu.org/software/bash/manual/bash.html#Bash-Conditional-Expressions-1

Not sure on your actual problem, though, are you setting the stage_url with http:// explicitly?

```ruby
set :stage_url, "http://123.123.123.123"
```

**Comment by 412andrewmortimer** [comment]
```
set :stage_url, "http://123.123.123.123"
```
Helped, I'm still getting my bearings within the repo. Thanks for you help!
