### ISSUE TITLE
It says slackify is optional, but actually all configs are already live upon install

### ISSUE THREAD

**Issue by lustremedia** [Mixd/wp-deploy#73]
Hi thanks for the deploy tool, I am just getting started, however I had some issues with comment out all the the slack configs and remove them from my Gemfile.

This is tedious. If it is optional as the ReadMe reads, then make it optional. It would be great if the slackify configs were commented out.

**Comment by lukewhitehouse** [comment]
Hi @lustremedia, we completely agree and its an oversight on our part. We'll be fixing this in the next release, for the time being, heres a quick step-by-step guide on how to remove the slack integration:

1. Remove the `config/slack.rb` file
2. Go to `config/deploy.rb and remove [line 5](https://github.com/Mixd/wp-deploy/blob/master/config/deploy.rb#L5)
