### ISSUE TITLE
prepare.sh still on 4.0 branch of wp

### ISSUE THREAD

**Issue by lustremedia** [Mixd/wp-deploy#76]
prepare.sh is on the 4.0 branch 4.2 is the newest.

```git submodule add -b 4.0-branch https://github.com/WordPress/WordPress.git wordpress```

How would I go about to change the submodule branch in a production environment since the core update does not work?

Also wouldn't it be better to run prepare.sh with getting the latest.zip rather than getting wordpress from github? The issue is that wordpress will always create a new branch for a new version. So the project would need to change branches in prepare.sh every time a new wp version comes out.

That is a lot of work for maintaining this project consistently!

**Comment by lukewhitehouse** [comment]
@lustremedia Good point, we need to update that. You can do this manually by doing the following:

```
$ cd wordpress
$ git fetch --tags
$ git checkout 4.2
```

Wordpress will then be on 4.2, to commit your changes do the following within the root of the project:

```
$ git add -A
$ git commit -m "update wordpress to 4.2"
```

**Comment by lustremedia** [comment]
Thanks for the pointers, however now I run into this.

```(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@192.168.56.101: git exit status: 1
git stdout: Nothing written
git stderr: fatal: Needed a single revision
Unable to find current revision in submodule path 'wordpress'

SSHKit::Command::Failed: git exit status: 1
git stdout: Nothing written
git stderr: fatal: Needed a single revision
Unable to find current revision in submodule path 'wordpress'

Tasks: TOP => git:create_release
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@192.168.56.101: git exit status: 1
git stdout: Nothing written
git stderr: fatal: Needed a single revision
Unable to find current revision in submodule path 'wordpress'```

**Comment by lustremedia** [comment]
Can I just drop the wordpress submodule and initialize it again? If so, how do I do that? Sorry I never worked with git submodules ...

**Comment by lukewhitehouse** [comment]
Try going into your server and deleting the `repo` folder, if that works then thats a bug with how wp-deploy handles the deployment of the submodule. We need to find a fix to this which we're planning on addressing in the next release.

**Comment by lukewhitehouse** [comment]
@lustremedia did you manage to sort this?

**Comment by lustremedia** [comment]
I managed to resolve the issue yes, however it will still not fix the prepare.sh being stuck on earlier WP versions which might have vulnerabilites etc. It should always get the latest wp source!

**Comment by lukewhitehouse** [comment]
@lustremedia agreed, will be addressed soon.

**Comment by lukewhitehouse** [comment]
@lustremedia checkout the [latest release](https://github.com/Mixd/wp-deploy/releases/tag/v1.2.1). Going to do final testing tomorrow.

**Comment by lustremedia** [comment]
@lukewhitehouse thanks! I'll give that a try when I have time.
