### ISSUE TITLE
Nginx setup complementing the .htaccess apache2

### ISSUE THREAD

**Issue by lustremedia** [Mixd/wp-deploy#77]
It would be nice to have an nginx (LEMP) type of setup that would complement the .htaccess LAMP/MAMP setup.

This would be a nice to have.

**Comment by lukewhitehouse** [comment]
@lustremedia definitely nice to have, however, none of our servers currently run on NGINX so it will be hard to maintain. Definitely one for the road map though :)

**Comment by clov3rly** [comment]
I think that'll be tough to write, as nginx doesn't have an equivalent to .htaccess... You need to set it all up in the nginx config, afaik. Let me know if you figure it out!

**Comment by lustremedia** [comment]
Agreed.
