### ISSUE TITLE
wp:setup:locally does not work

### ISSUE THREAD

**Issue by lustremedia** [Mixd/wp-deploy#78]
It looks like there is a problem with ```run_locally do``` block. Has this been tested when updating to Cap 3.4?
```cap staging wp:setup:local ```

Gives me following error:
```
(Backtrace restricted to imported tasks)
cap aborted!
NoMethodError: undefined method `[]' for nil:NilClass
.../capistrano/tasks/wp.cap:102:in `block (4 levels) in <top (required)>'
.../capistrano/tasks/wp.cap:83:in `block (3 levels) in <top (required)>' 
Tasks: TOP => wp:setup:local
(See full trace by running task with --trace)
```
83 is run_locally from sshkit

I have read on several github pages that run_locally is a bad idea, but didn't dig deeper. Maybe it would be better to use the local %x ruby syntax to run things. 
See:
http://capistranorb.com/documentation/getting-started/local-tasks

**Comment by lukewhitehouse** [comment]
@lustremedia `wp:setup:local` has been tested and I'm currently using it on a project at the moment. Can you provide the full debug message so I can help you further?

Nonetheless, I suspect there are quite a few functions and commands that we could do with replacing. Just to give you a little backstory, wp-deploy was originally created on Capistrano 2, however, was quickly ported over to Cap3 once it came out. Unfortunately, when Cap3 came out, there wasn't much documentation, or at least usable documentation ... therefore there may be areas that now seem a little long winded and perhaps bad practice.

We'll definitely look into this, thanks!

**Comment by lustremedia** [comment]
I am not sure what went wrong on my side ... but I set it up manually
