### ISSUE TITLE
How do we update previous versions of wp-deploy?

### ISSUE THREAD

**Issue by ryanjkoehler** [Mixd/wp-deploy#79]
Do I just replace all config files or is there a more elegant solution?

**Comment by lukewhitehouse** [comment]
@ryanjkoehler unfortunately so, we currently don't have a simple system in place to update this. We're most likely go down the root of packaging wp-deploy into a ruby gem. Any thoughts?

**Comment by clov3rly** [comment]
Sounds like the right path to take, imo. :+1:
