### ISSUE TITLE
wp:core:update to specific version

### ISSUE THREAD

**Issue by robertocinetto** [Mixd/wp-deploy#81]
Hi!
I'm trying to update Wordpress core by running

    cap production wp:core:update

The current public version of wp is 4.2.1, but my installation running the previous command will stay at 4.0.4.

I don't understand why. Is there a way to update to latest/specific version of wp? 

Thank you very much!

**Comment by clov3rly** [comment]
This is the same issue as #75, you can read the discussion there for a fix ;)

**Comment by robertocinetto** [comment]
Ok thank you! Fix worked for me too!
