### ISSUE TITLE
ExecuteError -> git checkout -B

### ISSUE THREAD

**Issue by burn4ever** [Mixd/wp-deploy#83]
Hi,
by setting up the staging environment with $ bundle exec cap staging wp:setup:remote
I receive the following error:

SSHKit::Runner::ExecuteError: Exception while executing as XXXXX: git exit status: 129
git stdout: Nothing written
git stderr: error: unknown switch `B'

Looks like the "git checkout $latestTag" in the wp.cap file creates the "git checkout -B" which is an unknown option. Any hint how I can handle this?

**Comment by lukewhitehouse** [comment]
@burn4ever Can you check the version of Git you're currently running on the server? It sounds like thats the problem. wp-deploy doesn't support 1.7.3 and below

**Comment by burn4ever** [comment]
yep, server has git 1.7.2.5 installed.
Will check or contact my hoster If it´s possible to upgrade
