### ISSUE TITLE
wp stderr: Error: This does not seem to be a WordPress install. 

### ISSUE THREAD

**Issue by joelataylor** [Mixd/wp-deploy#85]
Hi there, I'm running `cap production wp:setup:remote` and getting the error: `wp stderr: Error: This does not seem to be a WordPress install.`

This error surfaces when it get's to the `wp core install ...` command.

Suggestions?

**Comment by clov3rly** [comment]
Either you're not actually in the right folder, or as happens to me when I install Wordpress on a vagrant virtual box, you're in the host machine, not the guest machine

Callum Kerr

**Comment by joelataylor** [comment]
@clov3rly everything prior to this calls works. The remote server gets the directories created, it pulls from the repo, it creates the releases directories - does the symlinks - but it's NOT pulling down WordPress into a wordpress directory.

So therefore, the wp install command doesn't make sense. How is WP supposed to get onto the remote server?

**Comment by clov3rly** [comment]
If you log in to the remote server, can you find the wp install files? What happens if you run this command from the server itself?

`wp core install --url='#{wp_siteurl}' --title='#{title}' --admin_user='#{user}' --admin_password='#{password}' --admin_email='#{email}'` 

(Fill in your own or test values for #{title}, #{user}, etc...)

**Comment by joelataylor** [comment]
I got it - I had missed adding the WordPress submodule when creating my new
repo. Doh!

On Fri, May 29, 2015 at 4:49 PM, Callum Kerr <notifications@github.com>
wrote:

> If you log in to the remote server, can you find the wp install files?
> What happens if you run this command from the server itself?
>
> wp core install --url='#{wp_siteurl}' --title='#{title}'
> --admin_user='#{user}' --admin_password='#{password}'
> --admin_email='#{email}'
>
> (Fill in your own or test values for #{title}, #{user}, etc...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mixd/wp-deploy/issues/85#issuecomment-106930919>.
>



-- 
-------------------------------------------------------------
Joel A. Taylor
(615) 480-2010
http://joelataylor.com
