### ISSUE TITLE
Fatal error writing repro folder

### ISSUE THREAD

**Issue by Luckyfella73** [Mixd/wp-deploy#86]
Hi,
after a lot of struggle I nearly got a deployment process to work
executing: `bundle exec cap production wp:setup:remote`

My problem now is that I get this error message and don't know what to do about it:
`git stderr: fatal: destination path 'foldername/repo' already exists and is not an empty directory.`

In my production.rb I have this line:
`server "myServerAdress", user: "myUsername", roles: %w{web app db}`

I found this article:
http://stackoverflow.com/questions/24314972/capistrano-destination-path-already-exists-not-an-empty-directory

saying:

> I had the same problem. The reason is in double definition of the role and/or server. Try to remove

> server 'SERVER-IP', user: 'USERNAME', roles: %w{app}
> in production.rb and

> role :app, "SERVER-IP"
> in deploy.rb. The latter seems to be just simple syntax while the former - is extended one, so you in fact > you declare roles twice (three time to be more precise: 2 in production.rb and 1 in deploy.rb). Hope it > helps.

Any hints what I should try to solve that issue?
Best regards

**Comment by clov3rly** [comment]
Try running `bundle exec cap production cache:repo:purge`

**Comment by Luckyfella73** [comment]
I noticed that my GIT version was outdated - after updating git this error disappeared.
But thank you for the hint nevertheless!

Now the deploy process seems to nearly come to the end - now I get this error:
```
DEBUG [2830736f] Command: cd releases/20150701152703 && /usr/bin/env wp core install --url='http://www.ourDomain.de' --title='WP Deploy Check' --admin_user='admin_wp_deploy' --admin_password='lsCLbgVKSvAudokiUa' --admin_email='myName@ourDomain.de'
DEBUG [2830736f] 	/usr/bin/env:
DEBUG [2830736f] 	wp
DEBUG [2830736f] 	: No such file or directory
```

Everthing else in the terminal debug output before has no errors. So the WP git is successfully cloned to my server just the WP setup does not work.

Would be nice if you have an idea what I can do to solve this!
Best regards

**Comment by clov3rly** [comment]
If I'm getting an error in the deploy process, I often find it helpful to ssh in to the server, and run the same command in the appropriate directory. Being in the filesystem, it usually becomes more easily apparent where the error lies.

**Comment by lukewhitehouse** [comment]
Hi @Luckyfella73, @clov3rly makes a great point. Try going into the `/usr/bin/env` folder and check you can run everything correctly

**Comment by Luckyfella73** [comment]
Unfortunately I no server expert and don't know where to look.. I allready explored all directories created by the wp-deploy process but they are not included there.

Aaaahh I just found out that I missed to install the wp-cli on the production server.. sorry. I try to do that and let you know.

**Comment by lukewhitehouse** [comment]
@Luckyfella73 That'll explain the 3rd line in the error message! Let me know how you get on.

**Comment by Luckyfella73** [comment]
@lukewhitehouse It took a while for I have no permissions to use sudo on the server but finally I got the wp-cli to work :) the latest error disappeared now but I get this error message now:
```
SSHKit::Runner::ExecuteError: Exception while executing as sshUser@domain.com: wp exit status: 1
wp stdout: Nothing written
wp stderr: Error: wp-config.php not found.
Either create one manually or use `wp core config`.
```
I thought the wp-config.php file is created by the wp:setup:remote process - is that correct? Otherwise- where would I have to create the wp-config.php file or in what folder would I have to fire `wp core config`?

**Comment by lukewhitehouse** [comment]
@Luckyfella73 Glad you got the initial problem sorted. Yes, `wp:setup:remote` creates the `wp-config.php` file. It sounds like it can't find it. Can you go into your server and locate it from there?

**Comment by Luckyfella73** [comment]
@lukewhitehouse I have symlinks in each "releases/xyz" folders to wp-config.php and a wp-config.php file in "shared/".

I have to notice that the folder on remote server where WP is deployed to is not reachable by browser url - does that matter?

**Comment by joelataylor** [comment]
@Luckyfella73 can you provide the path you're referring to? Is your vhost setup to point to your `:deploy_to/current` directory? Does that dir exist on your server? What does the file listing in that dir look like?

**Comment by Luckyfella73** [comment]
@joelataylor thanks for your post! Just now I have no time left unfortunately but I appreciate your post very much and will get back to you as soon as I can!

Best regards!

**Comment by lukewhitehouse** [comment]
Hey @Luckyfella73, I'm going to close this for now but should you experience the problem in the future go ahead and let us know!
