### ISSUE TITLE
Local development on Vagrant

### ISSUE THREAD

**Issue by chrisRidgers** [Mixd/wp-deploy#88]
My current set up involves a Vagrant machine which mounts my project dir.  Any of my workmates can clone the project, run vagrant up and get a working install to work from.

With wp-deploy, how do I semantically re link my local files (uploads, themes, plugins etc)?

I can point my web server at the mounted project, but I'm pretty sure that would fail.

I don’t want to have to run a deploy task to view any changes ive made in my theme while developing out of my local box.

**Comment by bigmike7801** [comment]
Have you figured out a solution to this issue yet? I'd be interested in hearing it if you have.

**Comment by clov3rly** [comment]
@chrisRidgers @bigmike7801 
I think that part of your question is answered with the `uploads` task:
```bash
$ bundle exec cap production uploads:pull
$ bundle exec cap production uploads:push
```
If I understand the OP correctly, you are installing plugins / themes through the wp admin interface on your local box, and want to be able to sync them with your colleagues? I add any plugins and themes that I care about to the git repo, and so they are pulled in when ever the repo is cloned (and I handle plugin/theme updates in the same way, update through the admin interface locally, git add the modifications to `content/plugins` and commit, then run `cap production deploy`.

It is also possible to manage your third-party plugin/theme dependencies, using composer, and wpackagist.org, which will take a little setup, but keeps third-party code out of your repo. [Bedrock](https://github.com/roots/Bedrock) is a project that manages dependencies in this way, if you're interested in pursuing that path.

**Comment by bigmike7801** [comment]
I've actually been reading up on Bedrock for a while now. My issue is that I have (what I think to be) a somewhat unique situation.

I'm developing for 2 news websites. The development includes 2 custom plugins that both sites will use and then each site has their own custom theme. So I'm just having a difficult time on figuring out how to structure/deploy with this scenario.

**Comment by clov3rly** [comment]
With wp-deploy, I'd probably add the plugins as git submodules, and keep the custom theme as part of the main repo.

With bedrock, i'd add the custom plugins to packagist.org (really easy), and then add them as composer dependencies, and again, keep the custom theme as part of the main site repo for each site.

**Comment by bigmike7801** [comment]
I was leaning towards submodules. Just was confused as to whereI should do my "dev work" for the plugins. Should I create a separate VM just for each plugin or should I use the VM that I'm using to develop the themes for the two sites. Because if I use one of those sites, I don't see how I can add it as a submodule AND develop it.

**Comment by clov3rly** [comment]
You can develop inside a submodule. Once you're up and running, there shouldn't be any problems, so long as you run 'git submodule update' to pull in any updates to your git submodules after a git pull.

To set it up, you'll need to create the remote repo first, then run `git submodule add <repo-url> content/plugins/<your-plugin>`

Then you can `cd content/plugins/<your-plugin>` and develop exactly as you would in any other git repo. The VM will see the files, and you can modify them, git commit and git push etc...

**Comment by bigmike7801** [comment]
OK, I think I understand and will give that a shot.

Thank you.

**Comment by chrisRidgers** [comment]
I have not yet found a solution as my focus has been elsewhere, im trying to set some time aside this week to play with wp-deploy.
