### ISSUE TITLE
Question about using WP-CLI on the remote server

### ISSUE THREAD

**Issue by joelataylor** [Mixd/wp-deploy#89]
Hi, thanks for the repo - this has been really helpful!

I seem to be having an issue with using WP-CLI on my production server due to the `wp-config.php` file defining the `WP_CONTENT_DIR`. WordPress (on my server) only like's this version:
`define('WP_CONTENT_DIR', realpath($_SERVER['DOCUMENT_ROOT'] . '/content'));`

Where as I have to specify the explicit route for WP-CLI (and WP doesn't like this version):
`define('WP_CONTENT_DIR', '/home/webmaster/www/artisan/current/content');`

When using the version WP-CLI likes, my asset url's get all jacked:
`https://artisandesigngallery.com/content/plugins/home/webmaster/www/artisan/releases/20150622012955/content/plugins/gravityforms/css/readyclass.min.css`

Suggestions?

**Comment by lukewhitehouse** [comment]
Hey @joelataylor , thats strange. Why does your server require a full path like that? Sounds like somethings like installed on your server, what versions of Apache and PHP (etc) have you got?

**Comment by lukewhitehouse** [comment]
Alternatively, try commenting out this line

```
define('WP_CONTENT_DIR', realpath($_SERVER['DOCUMENT_ROOT'] . '/content'));
```

and use the [line above it](https://github.com/Mixd/wp-deploy/blob/master/config/templates/wp-config.php.erb#L25)

**Comment by lukewhitehouse** [comment]
@joelataylor any luck?

**Comment by joelataylor** [comment]
Hi @lukewhitehouse - sorry for the slow response! The `realpath(dirname(__FILE__)) . '/content';` option is the same as my second option above. It defines the local path on the server to the content directory, which WP-CLI likes, but WordPress doesn't.

I was going to create a `wp-cli.yml` to define the path there, but was wondering how this works for others and why I'm having issues.

I'm using Nginx/PHP-FPM if that means anything.

**Comment by joelataylor** [comment]
Here's a small update:
### WordPress
`realpath($_SERVER['DOCUMENT_ROOT'] . '/content')` => `/home/webmaster/www/artisan/current/content` [correct!]
`realpath(dirname(__FILE__) . '/content')` => `/home/webmaster/www/artisan/shared/content` [wrong!]

### WP-CLI
`realpath($_SERVER['DOCUMENT_ROOT'] . '/content')` => `/home/webmaster/www/artisan/releases/20150707053112/wordpress/content` [wrong!]
`realpath(dirname(__FILE__) . '/content')` => `/home/webmaster/www/artisan/shared/content` [wrong!]

PHP's `dirname` follows symlinks so I'm not sure how that works on other deployed servers that have a symlinked wp-config.php file. WP-CLI's `$_SERVER['DOCUMENT_ROOT']` is different from the servers setting - and this I'm not sure why.

I don't have any custom wp-cli.yml files changing my config - so I'm quite confused. But I'll keep digging.

**Comment by joelataylor** [comment]
Ok, so this is a solution (not sure if it's the best, but it's working):

```php
$doc_root = rtrim(str_replace('wordpress', '', $_SERVER['DOCUMENT_ROOT']), '/');
define('WP_CONTENT_DIR', realpath($doc_root . '/content'));
```

Thoughts @lukewhitehouse ?

**Comment by lukewhitehouse** [comment]
@joelataylor Its very strange that this hasn't cropped up sooner if this is basically the NGINX solution. We currently only work on Apache2 servers at the moment but we'll try to get this tested for everyone.

Alternatively, if anyone else has any insight then that'd be cool?
