### ISSUE TITLE
Suggestion for V2

### ISSUE THREAD

**Issue by joelataylor** [Mixd/wp-deploy#91]
Hi guys - nice to see V2 coming! :+1: 

One thing I've done with my version of `wp-deploy` is to switch out the SubmoduleStrategy class.

I'm using: https://github.com/ekho/capistrano-git-submodule-strategy/blob/master/lib/capistrano/git-submodule-strategy.rb
Which would fit nicely w/ your now pure Gem version of the process.

I found the current Strategy made a new folder in the remote `/repo` dir as the timestamp of the deployment, which meant that it would break if you tried to deploy a different branch.

Lemme know your thoughts.

**Comment by lukewhitehouse** [comment]
@joelataylor Cheers for the suggestion Joel. That sounds like a great idea and we'll have a look into it!
