### ISSUE TITLE
Large sites

### ISSUE THREAD

**Issue by roubenz** [Mixd/wp-deploy#92]
Hey, guys!
I'm experiencing some problems with large sites.
db push/pull comes without compression - it takes too long for database to be downloaded/search-replaced with wp-cli.
syncing uploads is completely impossible - it will take hours if not days. 

Is there something in plans for v2 to fix this ?

Ruben

**Comment by lukewhitehouse** [comment]
Hi @roubenz, thanks for the heads up. Compression is something we definitely want to tackle; as long as we don't get away from the core functionality that wp-deploy currently offers.

Just as a rule of thumb for when testing any new compression features, can you let me know any stats about this large site? Database size, columns etc. Uploads size, number of images, file types etc.

**Comment by roubenz** [comment]
Hi @lukewhitehouse,
Thanks for a quick response!

Here stats for smaller one:
Uploads folder: 30GB approx 400 000 files, images (jpg+png)
Database size: uncompressed dump: 800 MB, mysql data folder: 1GB, 48 tables.

For uploads folder, each image has 8-12 thumbnails, in average from 400KB to 5KB.

For bigger project I can't provide any stats here, but overall project size is over 150GB (including cache folder). I didn't even tried to use wp_deploy with it.

Since both upload files and database entries in wordpress are being changed very rarely for older ones, maybe it makes sense to try to implement something like incremental updates.

Some thoughts that may be useful:
- enable syncing only specific paths inside uploads. (sometimes only folder of last month is needed for development to be synced)
- some optional parameter to enable 'smart' syncing. Something that may check for example modification dates or calculate hashes (crc32 for example) to detect changed folders. Or even dumb --ignore-existing flag for rsync.
- Chunk database dump/data and checksum for older entries to transfer only changes (This may become a database migration system for Wordpress). I know, this point may be beyond the project, but still is related to development process and deployment.
- Compress database during transfer.
- wp search-replace is pretty slow. Maybe try to get rid of database queries, for example use 'sed' + some parser for serialized objects ? I'm still looking for a faster search-replace in C which works with php serialized objects :) I'll be back to you if I'll find one or I'll write one :D 

Thanks!
Ruben.

**Comment by clov3rly** [comment]
> some optional parameter to enable 'smart' syncing. Something that may check for example modification dates or calculate hashes (crc32 for example) to detect changed folders. Or even dumb --ignore-existing flag for rsync.

Rsync actually checks modification-times by default. From the man page:
> Normally rsync will skip any files that are already the same size and have the same modification timestamp. This option turns off this lqquick checkrq behavior, causing all files to be updated.

If you feel that it is not doing this correctly, you may investigate 
` --size-only`
>              Normally rsync will not transfer any files that are already  the
              same  size  and  have the same modification time-stamp. With the
              --size-only option, files will not be transferred if  they  have
              the  same  size,  regardless  of  timestamp. This is useful when
              starting to use rsync after using another mirroring system which
              may not preserve timestamps exactly.
 and you can force a checksum comparison with the `-c` or `--checksum` flag:
> This changes the way rsync checks if the files have been changed and are in need of a transfer. Without this option, rsync uses a lqquick checkrq that (by default) checks if each file's size and time of last modification match between the sender and receiver. This option changes this to compare a 128-bit checksum for each file that has a matching size. Generating the checksums means that both sides will expend a lot of disk I/O reading all the data in the files in the transfer (and this is prior to any reading that will be done to transfer changed files), so this can slow things down significantly.
But as the above quote notes, this can actually slow down the transfer, as you have to run an I/O intensive check over all of your 400,000 files

The uploads tasks are [here](https://github.com/Mixd/wp-deploy/blob/master/lib/capistrano/tasks/content.cap), and shouldn't be too hard to extend. As you can see, it is just calling rsync. You can override it or add your own task to add a filter to the rsync call.

The flags you should look at are `-f / --filter`, `--include=PATTERN` or `--include-form=FILE` where `FILE` is a file that contains contains include patterns (one per line), and `--exclude=PATTERN / --exclude-from=FILE`

Re: the database, currently the db:push task is uploading using sshkit's `upload! ` method, which I believe uses scp. You could quite easily override this method to upload using `rsync` instead, with the `-z` flag to enable over-the-wire compression. 

Hope that helps, that's a pretty big project you have there.

**Comment by roubenz** [comment]
Hey, @clov3rly !
Thanks for suggestions, I'll definitely try some of them.

For `rsync` - my goal is to minimize connections between servers. Usually old upload folders  are being changed very rarely, so there is no point to compare all files inside every time we do `push` or `pull`, especially if the site is under active development. Besides that, we are using Vagrant and ssh tunnel to reach production server, so its serious for me :)
What I'm thinking is about to `tar` directories and do filesize (or hash, or whatever) check for whole tarball, and if size doesn't match (or no enough free space on disk)  fall back to normal `rsync`. This may save checks/comparisons for hundred thousands files. It may be not the best solution, it is just initial thoughts I have here. `tar` may cause some disk IO problems I think (maybe `ionice` will help here). We can even never `tar` directories, but compare directory sizes and file amounts in them as a 'light' mode. 

I already modified some commands on my setup. What I'm trying to get now is some scalable solution for all kind of projects for all my team members to use (probably in a v2). In combination with additional push/pull options we will get something like this:

`cap produciton uploads:pull:minimizeconnections`
`cap staging uploads:push --path="2015/07"`
or even:
`cap production uploads:pull --command='rsync -azP remote:/path local:/path'`
`cap production uploads:run --command='custom_script.sh' # e.g. take a disk snapshot on zfs` 

So we can do it from terminal (or from a script) and not be forced to modify deployment/include files each time when something changes.

For DB - its a simple and elegant solution, I'll definitely try that, Thanks!

Regards,
Ruben.

P.S. Unfortunately I'm not that good in bash scripting or ruby to do whole `tar` thing I've described above, otherwise you could get a pull request :)
Thanks again!

**Comment by clov3rly** [comment]
While your idea with `tar` may work, and may save some time over `rsync -c`, I think if you instead ran something like...

```ruby
`rsync --include="uploads/#{Date.today.year}/{#{Date.today.month},#{Date.today.month - 1}}`
```

... you'll only be trying to sync the files from this month and last month, which will work for you so long as it was less than two months since you last pulled.

* NB: That snippet above may not work, Writing without checking out specifics or testing :P

**Comment by roubenz** [comment]
Thank you guys for a help.
I've ended up with this, let me know if you see any possible problems. 
Thanks!

#### [ Database ] 
db.cap (replace commented lines with a code below it)
```
#download! "#{fetch(:backup_file)}", "db_backups/#{fetch(:backup_filename)}.sql"
run_locally do
  roles(:all).each do |role|
    execute :rsync, "-avzOP" + (role.port ? " -e 'ssh -p #{role.port}'" : "") + " #{role.user}@#{role.hostname}:#{fetch(:backup_file)} db_backups/#{fetch(:backup_filename)}.sql"
    puts "#{role.port} #{role.user} #{role.hostname}"
  end
end

#====================

#upload! "db_backups/#{fetch(:backup_filename)}.sql", "#{fetch(:backup_file)}"

run_locally do
  roles(:all).each do |role|
    execute :rsync, "-avzO --progress" + " db_backups/#{fetch(:backup_filename)}.sql " + (role.port ? " -e 'ssh -p #{role.port}'" : "") + " #{role.user}@#{role.hostname}:#{fetch(:backup_file)} "
    puts "#{role.port} #{role.user} #{role.hostname}"
  end
end
```

#### [ Uploads ] 
content.cap (Whole file)
**Usage**: 
Syntax is the same both for push and pull
`cap production uploads:pull` - default behavior
`cap production uploads:push last=true ` - Only last month folder
`cap production uploads:push custom=some/path ` - push or pull provided some/path

Using Environment variables may not be a good idea, but its ok for my setup.
We can add also a regex matching for files, but currently I don't need this.

```
namespace :uploads do

  desc "Push any changed or new files from local to remote"
  task :push do
    run_locally do
        roles(:all).each do |role|
            if ENV['last'] && ENV['last'].casecmp("true") == 0
              month = "%02d" % Date.today.month
              year = "%04d" % Date.today.year
              execute :rsync, "-avzO" + (role.port ? " -e 'ssh -p #{role.port}'" : "") + " content/uploads/#{year}/#{month}/ #{role.user}@#{role.hostname}:#{shared_path}/content/uploads/#{year}/#{month}"
            end

            if ENV['custom']
              slash = ''
              if File.directory?("content/uploads/#{ENV['custom']}")
                slash = '/'
              end
              execute :rsync, "-avzO" + (role.port ? " -e 'ssh -p #{role.port}'" : "") + " content/uploads/#{ENV['custom']}#{slash} #{role.user}@#{role.hostname}:#{shared_path}/content/uploads/#{ENV['custom']}"
            end

            if !ENV['last'] && !ENV['custom']
              execute :rsync, "-avzO" + (role.port ? " -e 'ssh -p #{role.port}'" : "") + " content/uploads/ #{role.user}@#{role.hostname}:#{shared_path}/content/uploads"
            end
          end
      end
  end

  desc "Pull any changed or new files from remote to local"
  task :pull do

    run_locally do
        roles(:all).each do |role|
            if ENV['last'] && ENV['last'].casecmp("true") == 0
              month = "%02d" % Date.today.month
              year = "%04d" % Date.today.year
              execute :rsync, "-avzO" + (role.port ? " -e 'ssh -p #{role.port}'" : "") + " #{role.user}@#{role.hostname}:#{shared_path}/content/uploads/#{year}/#{month}/ content/uploads/#{year}/#{month}"
            end

            if ENV['custom']

              slash = ''
              on roles(:app) do
                  within release_path do
                     if test("[ -d #{shared_path}/content/uploads/#{ENV['custom']} ]")
                        slash = '/'
                     else
                        slash = ''
                     end
                  end
              end
              execute :rsync, "-avzO" + (role.port ? " -e 'ssh -p #{role.port}'" : "") + " #{role.user}@#{role.hostname}:#{shared_path}/content/uploads/#{ENV['custom']}#{slash} content/uploads/#{ENV['custom']}"
            end

            if !ENV['last'] && !ENV['custom']
              execute :rsync, "-avzO" + (role.port ? " -e 'ssh -p #{role.port}'" : "") + " #{role.user}@#{role.hostname}:#{shared_path}/content/uploads/ content/uploads"
            end
            #    execute :rsync, "-avzO" + (role.port ? " -e 'ssh -p #{role.port}'" : "") + " #{role.user}@#{role.hostname}:#{shared_path}/content/uploads/ content/uploads"
          end
      end
  end
end
```

**Comment by clov3rly** [comment]
Looks like you've got something that'll work for you. Just a style issue mainly, but especially if you're building this for your team and others to use too, I'd change the environment variables names: `last` => `last_month` and `custom` => `custom_path`. Extra couple of characters, lots more apparent meaning.

**Comment by clov3rly** [comment]
Also, you can syntax highlight using named fencing blocks, with three backticks which would encourage me to read your code :P

    ```ruby

```ruby
# your code here
def highlighting 
    u = awesome
    do { things } unless lazy
end
```

    ```

**Comment by roubenz** [comment]
Wow, thanks, I've edited my initial comment + added some comments if you are going to read it! :D
There are people in my team who totally agree with you, and yes, I've pasted it in case if someone else will have the same problem :)

**Comment by lukewhitehouse** [comment]
Cheers for going into this @roubenz & @clov3rly. We definitely need to look into a better method for migrations in general. We'll be tackling it in the next version of wp-deploy and will reference this issue :)
