### ISSUE TITLE
Feature Request for 2.0 - gemify

### ISSUE THREAD

**Issue by peterhoeg** [Mixd/wp-deploy#96]
It would be great if it could be turned into a standalone gem with a generator just for the bootstrapping bits. That would allow us to:
 - not have the source code part of the site being developed, and
 - update wp-deploy separately

**Comment by lukewhitehouse** [comment]
Hi @peterhoeg, thanks for your suggestion. We agree, moving wpdeploy into a gem is the right way forward and something we're already working on in v2. Its still very much in its early stages but take a look at the [beta](https://github.com/Mixd/wp-deploy/releases/tag/v2.0.0-beta)
